<?php
namespace Papyrillio\BeehiveBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Papyrillio\BeehiveBundle\Entity\Edition;
use DateTime;

class LoadEditionData extends AbstractFixture implements OrderedFixtureInterface
{
  
public static $EDITIONS = array(
  array('id' => 0, 'title' => 'Allgemeines', 'material' => 'Papyrus'),
  array('id' => 5, 'title' => 'P. Aberd.', 'material' => 'Papyrus'),
  array('id' => 10, 'title' => 'P. Abinn.', 'material' => 'Papyrus'),
  array('id' => 15, 'title' => 'P. Achmîm', 'material' => 'Papyrus'),
  array('id' => 20, 'title' => 'P. Adler', 'material' => 'Papyrus'),
  array('id' => 25, 'title' => 'P. Alex.', 'material' => 'Papyrus'),
  array('id' => 30, 'title' => 'P. Alex.Giss.', 'material' => 'Papyrus'),
  array('id' => 36, 'title' => 'P. Amh. 2', 'material' => 'Papyrus'),
  array('id' => 39, 'title' => 'P. Ammon', 'material' => 'Papyrus'),
  array('id' => 40, 'title' => 'P. Amst. 1', 'material' => 'Papyrus'),
  array('id' => 45, 'title' => 'P. Antin. 1', 'material' => 'Papyrus'),
  array('id' => 46, 'title' => 'P. Antin. 2', 'material' => 'Papyrus'),
  array('id' => 47, 'title' => 'P. Antin. 3', 'material' => 'Papyrus'),
  array('id' => 49, 'title' => 'P. Apa Apollo', 'material' => 'Papyrus'),
  array('id' => 50, 'title' => 'P. Apoll.', 'material' => 'Papyrus'),
  array('id' => 55, 'title' => 'Archiv 1', 'material' => 'Papyrus'),
  array('id' => 56, 'title' => 'Archiv 2', 'material' => 'Papyrus'),
  array('id' => 57, 'title' => 'Archiv 3', 'material' => 'Papyrus'),
  array('id' => 58, 'title' => 'Archiv 4', 'material' => 'Papyrus'),
  array('id' => 59, 'title' => 'Archiv 5', 'material' => 'Papyrus'),
  array('id' => 65, 'title' => 'P. Ashm. 1', 'material' => 'Papyrus'),
  array('id' => 70, 'title' => 'P. Baden 2', 'material' => 'Papyrus'),
  array('id' => 71, 'title' => 'P. Baden 4', 'material' => 'Papyrus'),
  array('id' => 72, 'title' => 'P. Baden 6', 'material' => 'Papyrus'),
  array('id' => 74, 'title' => 'P. Bala’izah 2', 'material' => 'Papyrus'),
  array('id' => 75, 'title' => 'P. Bas.', 'material' => 'Papyrus'),
  array('id' => 80, 'title' => 'P. Beatty Panop.', 'material' => 'Papyrus'),
  array('id' => 81, 'title' => 'P. Ben.Mus. 1', 'material' => 'Papyrus'),
  array('id' => 85, 'title' => 'B.G.U. 1', 'material' => 'Papyrus'),
  array('id' => 86, 'title' => 'B.G.U. 2', 'material' => 'Papyrus'),
  array('id' => 87, 'title' => 'B.G.U. 3', 'material' => 'Papyrus'),
  array('id' => 88, 'title' => 'B.G.U. 4', 'material' => 'Papyrus'),
  array('id' => 89, 'title' => 'B.G.U. 5', 'material' => 'Papyrus'),
  array('id' => 90, 'title' => 'B.G.U. 6', 'material' => 'Papyrus'),
  array('id' => 91, 'title' => 'B.G.U. 7', 'material' => 'Papyrus'),
  array('id' => 92, 'title' => 'B.G.U. 8', 'material' => 'Papyrus'),
  array('id' => 93, 'title' => 'B.G.U. 9', 'material' => 'Papyrus'),
  array('id' => 94, 'title' => 'B.G.U. 10', 'material' => 'Papyrus'),
  array('id' => 95, 'title' => 'B.G.U. 11', 'material' => 'Papyrus'),
  array('id' => 96, 'title' => 'B.G.U. 12', 'material' => 'Papyrus'),
  array('id' => 97, 'title' => 'B.G.U. 13', 'material' => 'Papyrus'),
  array('id' => 98, 'title' => 'B.G.U. 14', 'material' => 'Papyrus'),
  array('id' => 99, 'title' => 'B.G.U. 15', 'material' => 'Papyrus'),
  array('id' => 100, 'title' => 'B.G.U. 16', 'material' => 'Papyrus'),
  array('id' => 101, 'title' => 'B.G.U. 17', 'material' => 'Papyrus'),
  array('id' => 102, 'title' => 'B.G.U. 18 (P. Berl.Bork. → P. Panop.Borkowski)', 'material' => 'Papyrus'),
  array('id' => 125, 'title' => 'P. Berl.Frisk', 'material' => 'Papyrus'),
  array('id' => 130, 'title' => 'P. Berl.Leihg. 1', 'material' => 'Papyrus'),
  array('id' => 131, 'title' => 'P. Berl.Leihg. 2', 'material' => 'Papyrus'),
  array('id' => 135, 'title' => 'P. Berl.Möller', 'material' => 'Papyrus'),
  array('id' => 138, 'title' => 'P. Berl.Salmen.', 'material' => 'Papyrus'),
  array('id' => 140, 'title' => 'P. Berl.Sarischouli', 'material' => 'Papyrus'),
  array('id' => 145, 'title' => 'P. Berl.Zilliacus', 'material' => 'Papyrus'),
  array('id' => 146, 'title' => 'P. Bingen', 'material' => 'Papyrus'),
  array('id' => 147, 'title' => 'P. Bodl. 1', 'material' => 'Papyrus'),
  array('id' => 150, 'title' => 'P. Bon.', 'material' => 'Papyrus'),
  array('id' => 155, 'title' => 'P. Bouriant', 'material' => 'Papyrus'),
  array('id' => 160, 'title' => 'P. Brem.', 'material' => 'Papyrus'),
  array('id' => 163, 'title' => 'P. Brooklyn', 'material' => 'Papyrus'),
  array('id' => 165, 'title' => 'P. Brux. 1', 'material' => 'Papyrus'),
  array('id' => 166, 'title' => 'P. Brux. 2', 'material' => 'Papyrus'),
  array('id' => 167, 'title' => 'P. Bub. 1', 'material' => 'Papyrus'),
  array('id' => 168, 'title' => 'P. Bub. 2', 'material' => 'Papyrus'),
  array('id' => 170, 'title' => 'P. Cairo Goodspeed', 'material' => 'Papyrus'),
  array('id' => 174, 'title' => 'P. Cairo Isidor.', 'material' => 'Papyrus'),
  array('id' => 175, 'title' => 'P. Cairo Masp. 1', 'material' => 'Papyrus'),
  array('id' => 176, 'title' => 'P. Cairo Masp. 2', 'material' => 'Papyrus'),
  array('id' => 177, 'title' => 'P. Cairo Masp. 3', 'material' => 'Papyrus'),
  array('id' => 180, 'title' => 'P. Cairo Mich.', 'material' => 'Papyrus'),
  array('id' => 185, 'title' => 'P. Cairo Preis.', 'material' => 'Papyrus'),
  array('id' => 190, 'title' => 'P. Cairo Zen. 1', 'material' => 'Papyrus'),
  array('id' => 191, 'title' => 'P. Cairo Zen. 2', 'material' => 'Papyrus'),
  array('id' => 192, 'title' => 'P. Cairo Zen. 3', 'material' => 'Papyrus'),
  array('id' => 193, 'title' => 'P. Cairo Zen. 4', 'material' => 'Papyrus'),
  array('id' => 194, 'title' => 'P. Cairo Zen. 5', 'material' => 'Papyrus'),
  array('id' => 200, 'title' => 'P. Charite', 'material' => 'Papyrus'),
  array('id' => 205, 'title' => 'Chartae Latinae 1', 'material' => 'Papyrus'),
  array('id' => 206, 'title' => 'Chartae Latinae 2', 'material' => 'Papyrus'),
  array('id' => 207, 'title' => 'Chartae Latinae 3', 'material' => 'Papyrus'),
  array('id' => 208, 'title' => 'Chartae Latinae 4', 'material' => 'Papyrus'),
  array('id' => 209, 'title' => 'Chartae Latinae 5', 'material' => 'Papyrus'),
  array('id' => 210, 'title' => 'Chartae Latinae 6', 'material' => 'Papyrus'),
  array('id' => 211, 'title' => 'Chartae Latinae 7', 'material' => 'Papyrus'),
  array('id' => 212, 'title' => 'Chartae Latinae 8', 'material' => 'Papyrus'),
  array('id' => 213, 'title' => 'Chartae Latinae 9', 'material' => 'Papyrus'),
  array('id' => 214, 'title' => 'Chartae Latinae 10', 'material' => 'Papyrus'),
  array('id' => 215, 'title' => 'Chartae Latinae 11', 'material' => 'Papyrus'),
  array('id' => 216, 'title' => 'Chartae Latinae 12', 'material' => 'Papyrus'),
  array('id' => 217, 'title' => 'Chartae Latinae 13', 'material' => 'Papyrus'),
  array('id' => 218, 'title' => 'Chartae Latinae 14', 'material' => 'Papyrus'),
  array('id' => 219, 'title' => 'Chartae Latinae 15', 'material' => 'Papyrus'),
  array('id' => 220, 'title' => 'Chartae Latinae 16', 'material' => 'Papyrus'),
  array('id' => 221, 'title' => 'Chartae Latinae 17', 'material' => 'Papyrus'),
  array('id' => 222, 'title' => 'Chartae Latinae 18', 'material' => 'Papyrus'),
  array('id' => 223, 'title' => 'Chartae Latinae 19', 'material' => 'Papyrus'),
  array('id' => 224, 'title' => 'Chartae Latinae 20', 'material' => 'Papyrus'),
  array('id' => 225, 'title' => 'Chartae Latinae 21', 'material' => 'Papyrus'),
  array('id' => 226, 'title' => 'Chartae Latinae 22', 'material' => 'Papyrus'),
  array('id' => 227, 'title' => 'Chartae Latinae 23', 'material' => 'Papyrus'),
  array('id' => 228, 'title' => 'Chartae Latinae 24', 'material' => 'Papyrus'),
  array('id' => 229, 'title' => 'Chartae Latinae 25', 'material' => 'Papyrus'),
  array('id' => 230, 'title' => 'Chartae Latinae 26', 'material' => 'Papyrus'),
  array('id' => 231, 'title' => 'Chartae Latinae 27', 'material' => 'Papyrus'),
  array('id' => 232, 'title' => 'Chartae Latinae 28', 'material' => 'Papyrus'),
  array('id' => 233, 'title' => 'Chartae Latinae 29', 'material' => 'Papyrus'),
  array('id' => 234, 'title' => 'Chartae Latinae 30', 'material' => 'Papyrus'),
  array('id' => 235, 'title' => 'Chartae Latinae 43', 'material' => 'Papyrus'),
  array('id' => 236, 'title' => 'Chartae Latinae 47', 'material' => 'Papyrus'),
  array('id' => 255, 'title' => 'P. Chic.', 'material' => 'Papyrus'),
  array('id' => 257, 'title' => 'P. Chic.Hawara', 'material' => 'Papyrus'),
  array('id' => 265, 'title' => 'P. Coll.Youtie 1', 'material' => 'Papyrus'),
  array('id' => 266, 'title' => 'P. Coll.Youtie 2', 'material' => 'Papyrus'),
  array('id' => 270, 'title' => 'P. Colt Ness. 3', 'material' => 'Papyrus'),
  array('id' => 275, 'title' => 'P. Col. 1', 'material' => 'Papyrus'),
  array('id' => 276, 'title' => 'P. Col. 2', 'material' => 'Papyrus'),
  array('id' => 277, 'title' => 'P. Col. 5', 'material' => 'Papyrus'),
  array('id' => 278, 'title' => 'P. Col. 6', 'material' => 'Papyrus'),
  array('id' => 279, 'title' => 'P. Col. 7', 'material' => 'Papyrus'),
  array('id' => 280, 'title' => 'P. Col. 8', 'material' => 'Papyrus'),
  array('id' => 281, 'title' => 'P. Col. 9', 'material' => 'Papyrus'),
  array('id' => 282, 'title' => 'P. Col. 10', 'material' => 'Papyrus'),
  array('id' => 283, 'title' => 'P. Col. 11', 'material' => 'Papyrus'),
  array('id' => 285, 'title' => 'P. Col.Zen. 1', 'material' => 'Papyrus'),
  array('id' => 286, 'title' => 'P. Col.Zen. 2', 'material' => 'Papyrus'),
  array('id' => 287, 'title' => 'P. XV Congr.', 'material' => 'Papyrus'),
  array('id' => 290, 'title' => 'P. Cornell', 'material' => 'Papyrus'),
  array('id' => 295, 'title' => 'C.E.M.L.', 'material' => 'Papyrus'),
  array('id' => 300, 'title' => 'C.Ord.Ptol.', 'material' => 'Papyrus'),
  array('id' => 305, 'title' => 'C.P.J. 1', 'material' => 'Papyrus'),
  array('id' => 306, 'title' => 'C.P.J. 2', 'material' => 'Papyrus'),
  array('id' => 310, 'title' => 'C.P.R. 1', 'material' => 'Papyrus'),
  array('id' => 311, 'title' => 'C.P.R. 4', 'material' => 'Papyrus'),
  array('id' => 312, 'title' => 'C.P.R. 5', 'material' => 'Papyrus'),
  array('id' => 313, 'title' => 'C.P.R. 6', 'material' => 'Papyrus'),
  array('id' => 314, 'title' => 'C.P.R. 7', 'material' => 'Papyrus'),
  array('id' => 315, 'title' => 'C.P.R. 8', 'material' => 'Papyrus'),
  array('id' => 316, 'title' => 'C.P.R. 9', 'material' => 'Papyrus'),
  array('id' => 317, 'title' => 'C.P.R. 10', 'material' => 'Papyrus'),
  array('id' => 318, 'title' => 'C.P.R. 11', 'material' => 'Papyrus'),
  array('id' => 319, 'title' => 'C.P.R. 12', 'material' => 'Papyrus'),
  array('id' => 320, 'title' => 'C.P.R. 13', 'material' => 'Papyrus'),
  array('id' => 321, 'title' => 'C.P.R. 14', 'material' => 'Papyrus'),
  array('id' => 322, 'title' => 'C.P.R. 15', 'material' => 'Papyrus'),
  array('id' => 324, 'title' => 'C.P.R. 17A', 'material' => 'Papyrus'),
  array('id' => 325, 'title' => 'C.P.R. 17B', 'material' => 'Papyrus'),
  array('id' => 326, 'title' => 'C.P.R. 18', 'material' => 'Papyrus'),
  array('id' => 326, 'title' => 'C.P.R. 19', 'material' => 'Papyrus', 'idNew' => 326001),
  array('id' => 327, 'title' => 'C.P.R. 21', 'material' => 'Papyrus'),
  array('id' => 335, 'title' => 'P. Customs', 'material' => 'Papyrus'),
  array('id' => 337, 'title' => 'P. Diog.', 'material' => 'Papyrus'),
  array('id' => 338, 'title' => 'P. Doc.Masada', 'material' => 'Papyrus'),
  array('id' => 339, 'title' => 'P. Dub.', 'material' => 'Papyrus'),
  array('id' => 340, 'title' => 'P. Dura', 'material' => 'Papyrus'),
  array('id' => 345, 'title' => 'P. Edfou 1', 'material' => 'Papyrus'),
  array('id' => 346, 'title' => 'P. Edfou 2', 'material' => 'Papyrus'),
  array('id' => 350, 'title' => 'P. Eleph.', 'material' => 'Papyrus'),
  array('id' => 351, 'title' => 'P. Eleph. D.A.I.K.', 'material' => 'Papyrus'),
  array('id' => 355, 'title' => 'P. Enteuxeis', 'material' => 'Papyrus'),
  array('id' => 360, 'title' => 'P. Erasm. 1', 'material' => 'Papyrus'),
  array('id' => 361, 'title' => 'P. Erasm. 2', 'material' => 'Papyrus'),
  array('id' => 365, 'title' => 'P. Erlangen', 'material' => 'Papyrus'),
  array('id' => 370, 'title' => 'P. Fay.', 'material' => 'Papyrus'),
  array('id' => 375, 'title' => 'P. Flor. 1', 'material' => 'Papyrus'),
  array('id' => 376, 'title' => 'P. Flor. 2', 'material' => 'Papyrus'),
  array('id' => 377, 'title' => 'P. Flor. 3', 'material' => 'Papyrus'),
  array('id' => 380, 'title' => 'P. Fouad', 'material' => 'Papyrus'),
  array('id' => 385, 'title' => 'P. Fouad Crawford', 'material' => 'Papyrus'),
  array('id' => 390, 'title' => 'P. Frankf.', 'material' => 'Papyrus'),
  array('id' => 395, 'title' => 'P. Freib. 1', 'material' => 'Papyrus'),
  array('id' => 396, 'title' => 'P. Freib. 2', 'material' => 'Papyrus'),
  array('id' => 397, 'title' => 'P. Freib. 3', 'material' => 'Papyrus'),
  array('id' => 398, 'title' => 'P. Freib. 4', 'material' => 'Papyrus'),
  array('id' => 405, 'title' => 'P. Genf 1', 'material' => 'Papyrus'),
  array('id' => 406, 'title' => 'P. Genf 2', 'material' => 'Papyrus'),
  array('id' => 407, 'title' => 'P. Genf 3', 'material' => 'Papyrus'),
  array('id' => 408, 'title' => 'P. Genf 12', 'material' => 'Papyrus'),
  array('id' => 415, 'title' => 'P. Giss.', 'material' => 'Papyrus'),
  array('id' => 418, 'title' => 'P. Giss.Apoll.', 'material' => 'Papyrus'),
  array('id' => 420, 'title' => 'P. Giss.Bibl. 1', 'material' => 'Papyrus'),
  array('id' => 421, 'title' => 'P. Giss.Bibl. 2', 'material' => 'Papyrus'),
  array('id' => 422, 'title' => 'P. Giss.Bibl. 3', 'material' => 'Papyrus'),
  array('id' => 423, 'title' => 'P. Giss.Bibl. 4', 'material' => 'Papyrus'),
  array('id' => 424, 'title' => 'P. Giss.Bibl. 5', 'material' => 'Papyrus'),
  array('id' => 425, 'title' => 'P. Giss.Bibl. 6', 'material' => 'Papyrus'),
  array('id' => 435, 'title' => 'P. Got.', 'material' => 'Papyrus'),
  array('id' => 440, 'title' => 'P. Grad.', 'material' => 'Papyrus'),
  array('id' => 442, 'title' => 'P. Graux 2', 'material' => 'Papyrus'),
  array('id' => 443, 'title' => 'P. Graux 3', 'material' => 'Papyrus'),
  array('id' => 445, 'title' => 'P. Grenf. 1', 'material' => 'Papyrus'),
  array('id' => 446, 'title' => 'P. Grenf. 2', 'material' => 'Papyrus'),
  array('id' => 450, 'title' => 'P. Gron.', 'material' => 'Papyrus'),
  array('id' => 455, 'title' => 'P. Gurob', 'material' => 'Papyrus'),
  array('id' => 460, 'title' => 'P. Hal.', 'material' => 'Papyrus'),
  array('id' => 465, 'title' => 'P. Hamb. 1', 'material' => 'Papyrus'),
  array('id' => 466, 'title' => 'P. Hamb. 2', 'material' => 'Papyrus'),
  array('id' => 467, 'title' => 'P. Hamb. 3', 'material' => 'Papyrus'),
  array('id' => 468, 'title' => 'P. Hamb. 4', 'material' => 'Papyrus'),
  array('id' => 469, 'title' => 'P. Harrauer', 'material' => 'Papyrus'),
  array('id' => 470, 'title' => 'P. Harr. 1', 'material' => 'Papyrus'),
  array('id' => 471, 'title' => 'P. Harr. 2', 'material' => 'Papyrus'),
  array('id' => 475, 'title' => 'P. Haun. 1', 'material' => 'Papyrus'),
  array('id' => 476, 'title' => 'P. Haun. 2', 'material' => 'Papyrus'),
  array('id' => 477, 'title' => 'P. Haun. 3', 'material' => 'Papyrus'),
  array('id' => 480, 'title' => 'P. Heid. 1', 'material' => 'Papyrus'),
  array('id' => 481, 'title' => 'P. Heid. 2', 'material' => 'Papyrus'),
  array('id' => 482, 'title' => 'P. Heid. 3', 'material' => 'Papyrus'),
  array('id' => 483, 'title' => 'P. Heid. 4', 'material' => 'Papyrus'),
  array('id' => 484, 'title' => 'P. Heid. 5', 'material' => 'Papyrus'),
  array('id' => 485, 'title' => 'P. Heid. 6', 'material' => 'Papyrus'),
  array('id' => 486, 'title' => 'P. Heid. 7', 'material' => 'Papyrus'),
  array('id' => 487, 'title' => 'P. Heid. 8', 'material' => 'Papyrus'),
  array('id' => 488, 'title' => 'P. Hels. 1', 'material' => 'Papyrus'),
  array('id' => 490, 'title' => 'P. Herm.Rees', 'material' => 'Papyrus'),
  array('id' => 492, 'title' => 'P. Hever', 'material' => 'Papyrus'),
  array('id' => 495, 'title' => 'P. Hib. 1', 'material' => 'Papyrus'),
  array('id' => 496, 'title' => 'P. Hib. 2', 'material' => 'Papyrus'),
  array('id' => 500, 'title' => 'P. I.F.A.O. 1', 'material' => 'Papyrus'),
  array('id' => 501, 'title' => 'P. I.F.A.O. 2', 'material' => 'Papyrus'),
  array('id' => 502, 'title' => 'P. I.F.A.O. 3', 'material' => 'Papyrus'),
  array('id' => 505, 'title' => 'P. Jand. 2', 'material' => 'Papyrus'),
  array('id' => 506, 'title' => 'P. Jand. 3', 'material' => 'Papyrus'),
  array('id' => 507, 'title' => 'P. Jand. 4', 'material' => 'Papyrus'),
  array('id' => 508, 'title' => 'P. Jand. 5', 'material' => 'Papyrus'),
  array('id' => 509, 'title' => 'P. Jand. 6', 'material' => 'Papyrus'),
  array('id' => 510, 'title' => 'P. Jand. 7', 'material' => 'Papyrus'),
  array('id' => 511, 'title' => 'P. Jand. 8', 'material' => 'Papyrus'),
  array('id' => 513, 'title' => 'P.Jud.Des.Misc.', 'material' => 'Papyrus'),
  array('id' => 515, 'title' => 'P. Kellis 1', 'material' => 'Papyrus'),
  array('id' => 518, 'title' => 'P. Kellis 4 Gr. 96', 'material' => 'Papyrus'),
  array('id' => 520, 'title' => 'P. Köln 1', 'material' => 'Papyrus'),
  array('id' => 521, 'title' => 'P. Köln 2', 'material' => 'Papyrus'),
  array('id' => 522, 'title' => 'P. Köln 3', 'material' => 'Papyrus'),
  array('id' => 523, 'title' => 'P. Köln 4', 'material' => 'Papyrus'),
  array('id' => 524, 'title' => 'P. Köln 5', 'material' => 'Papyrus'),
  array('id' => 525, 'title' => 'P. Köln 6', 'material' => 'Papyrus'),
  array('id' => 526, 'title' => 'P. Köln 7', 'material' => 'Papyrus'),
  array('id' => 527, 'title' => 'P. Köln 8', 'material' => 'Papyrus'),
  array('id' => 528, 'title' => 'P. Köln 9', 'material' => 'Papyrus'),
  array('id' => 530, 'title' => 'P. Köln ägypt. 1', 'material' => 'Papyrus'),
  array('id' => 540, 'title' => 'P. Kron.', 'material' => 'Papyrus'),
  array('id' => 545, 'title' => 'P. Landlisten', 'material' => 'Papyrus'),
  array('id' => 550, 'title' => 'P. Laur. 1', 'material' => 'Papyrus'),
  array('id' => 551, 'title' => 'P. Laur. 2', 'material' => 'Papyrus'),
  array('id' => 552, 'title' => 'P. Laur. 3', 'material' => 'Papyrus'),
  array('id' => 553, 'title' => 'P. Laur. 4', 'material' => 'Papyrus'),
  array('id' => 554, 'title' => 'P. Laur. 5', 'material' => 'Papyrus'),
  array('id' => 565, 'title' => 'P. Leid.', 'material' => 'Papyrus'),
  array('id' => 570, 'title' => 'P. Leit.', 'material' => 'Papyrus'),
  array('id' => 575, 'title' => 'P. Lille 1', 'material' => 'Papyrus'),
  array('id' => 576, 'title' => 'P. Lille 2', 'material' => 'Papyrus'),
  array('id' => 579, 'title' => 'P. Lips.', 'material' => 'Papyrus'),
  array('id' => 579, 'title' => 'P. Lips. 2', 'material' => 'Papyrus', 'idNew' => 579001),
  array('id' => 580, 'title' => 'P. Lond. 1', 'material' => 'Papyrus'),
  array('id' => 581, 'title' => 'P. Lond. 2', 'material' => 'Papyrus'),
  array('id' => 582, 'title' => 'P. Lond. 3', 'material' => 'Papyrus'),
  array('id' => 583, 'title' => 'P. Lond. 4', 'material' => 'Papyrus'),
  array('id' => 584, 'title' => 'P. Lond. 5', 'material' => 'Papyrus'),
  array('id' => 585, 'title' => 'P. Lond. 6', 'material' => 'Papyrus'),
  array('id' => 586, 'title' => 'P. Lond. 7', 'material' => 'Papyrus'),
  array('id' => 587, 'title' => 'P. Louvre 1', 'material' => 'Papyrus'),
  array('id' => 590, 'title' => 'P. L.Bat. 1', 'material' => 'Papyrus'),
  array('id' => 591, 'title' => 'P. L.Bat. 2', 'material' => 'Papyrus'),
  array('id' => 592, 'title' => 'P. L.Bat. 3', 'material' => 'Papyrus'),
  array('id' => 593, 'title' => 'P. L.Bat. 5', 'material' => 'Papyrus'),
  array('id' => 594, 'title' => 'P. L.Bat. 6', 'material' => 'Papyrus'),
  array('id' => 595, 'title' => 'P. L.Bat. 11', 'material' => 'Papyrus'),
  array('id' => 596, 'title' => 'P. L.Bat. 13', 'material' => 'Papyrus'),
  array('id' => 597, 'title' => 'P. L.Bat. 16', 'material' => 'Papyrus'),
  array('id' => 598, 'title' => 'P. L.Bat. 17', 'material' => 'Papyrus'),
  array('id' => 599, 'title' => 'P. L.Bat. 19', 'material' => 'Papyrus'),
  array('id' => 600, 'title' => 'P. L.Bat. 20', 'material' => 'Papyrus'),
  array('id' => 601, 'title' => 'P. L.Bat. 22', 'material' => 'Papyrus'),
  array('id' => 602, 'title' => 'P. L.Bat. 23', 'material' => 'Papyrus'),
  array('id' => 603, 'title' => 'P. L.Bat. 25', 'material' => 'Papyrus'),
  array('id' => 604, 'title' => 'P. L.Bat. 26', 'material' => 'Papyrus'),
  array('id' => 605, 'title' => 'P. L.Bat. 27', 'material' => 'Papyrus'),
  array('id' => 607, 'title' => 'P. L.Bat. 29', 'material' => 'Papyrus'),
  array('id' => 608, 'title' => 'P. L.Bat. 30', 'material' => 'Papyrus'),
  array('id' => 609, 'title' => 'P.L.Bat. 32', 'material' => 'Papyrus'),
  array('id' => 614, 'title' => 'P. Lund. 1', 'material' => 'Papyrus'),
  array('id' => 615, 'title' => 'P. Lund 2', 'material' => 'Papyrus'),
  array('id' => 616, 'title' => 'P. Lund 3', 'material' => 'Papyrus'),
  array('id' => 617, 'title' => 'P. Lund 4', 'material' => 'Papyrus'),
  array('id' => 618, 'title' => 'P. Lund 6', 'material' => 'Papyrus'),
  array('id' => 625, 'title' => 'P. Marmarica (P. Masada → P. Doc.Masada)', 'material' => 'Papyrus'),
  array('id' => 627, 'title' => 'P. Matr.', 'material' => 'Papyrus'),
  array('id' => 630, 'title' => 'P. Medinet Madi', 'material' => 'Papyrus'),
  array('id' => 635, 'title' => 'P. Med. 1 Aufl. 1', 'material' => 'Papyrus'),
  array('id' => 636, 'title' => 'P. Med. 1 Aufl. 2', 'material' => 'Papyrus'),
  array('id' => 640, 'title' => 'P. Merton 1', 'material' => 'Papyrus'),
  array('id' => 641, 'title' => 'P. Merton 2', 'material' => 'Papyrus'),
  array('id' => 642, 'title' => 'P. Merton 3', 'material' => 'Papyrus'),
  array('id' => 645, 'title' => 'P. Meyer', 'material' => 'Papyrus'),
  array('id' => 650, 'title' => 'Meyer, Juristische Papyri', 'material' => 'Papyrus'),
  array('id' => 655, 'title' => 'P. Michael.', 'material' => 'Papyrus'),
  array('id' => 660, 'title' => 'P. Mich. 2', 'material' => 'Papyrus'),
  array('id' => 661, 'title' => 'P. Mich. 3', 'material' => 'Papyrus'),
  array('id' => 662, 'title' => 'P. Mich. 4 Teil 1', 'material' => 'Papyrus'),
  array('id' => 663, 'title' => 'P. Mich. 4 Teil 2', 'material' => 'Papyrus'),
  array('id' => 664, 'title' => 'P. Mich. 5', 'material' => 'Papyrus'),
  array('id' => 665, 'title' => 'P. Mich. 6', 'material' => 'Papyrus'),
  array('id' => 666, 'title' => 'P. Mich. 7', 'material' => 'Papyrus'),
  array('id' => 667, 'title' => 'P. Mich. 8', 'material' => 'Papyrus'),
  array('id' => 668, 'title' => 'P. Mich. 9', 'material' => 'Papyrus'),
  array('id' => 669, 'title' => 'P. Mich. 10', 'material' => 'Papyrus'),
  array('id' => 670, 'title' => 'P. Mich. 11', 'material' => 'Papyrus'),
  array('id' => 671, 'title' => 'P. Mich. 12', 'material' => 'Papyrus'),
  array('id' => 672, 'title' => 'P. Mich. 13', 'material' => 'Papyrus'),
  array('id' => 673, 'title' => 'P. Mich. 14', 'material' => 'Papyrus'),
  array('id' => 674, 'title' => 'P. Mich. 15', 'material' => 'Papyrus'),
  array('id' => 675, 'title' => 'P. Mich. 16', 'material' => 'Papyrus'),
  array('id' => 676, 'title' => 'P. Mich. 17', 'material' => 'Papyrus'),
  array('id' => 677, 'title' => 'P. Mich. 18', 'material' => 'Papyrus'),
  array('id' => 678, 'title' => 'P. Mich. 19', 'material' => 'Papyrus'),
  array('id' => 685, 'title' => 'P. Mich.Zen.', 'material' => 'Papyrus'),
  array('id' => 690, 'title' => 'P. Mil.', 'material' => 'Papyrus'),
  array('id' => 695, 'title' => 'P. Mil.Vogl. 1', 'material' => 'Papyrus'),
  array('id' => 696, 'title' => 'P. Mil.Vogl. 2', 'material' => 'Papyrus'),
  array('id' => 697, 'title' => 'P. Mil.Vogl. 3', 'material' => 'Papyrus'),
  array('id' => 698, 'title' => 'P. Mil.Vogl. 4', 'material' => 'Papyrus'),
  array('id' => 699, 'title' => 'P. Mil.Vogl. 6', 'material' => 'Papyrus'),
  array('id' => 700, 'title' => 'P. Mil.Vogl. 7', 'material' => 'Papyrus'),
  array('id' => 705, 'title' => 'M.P.E.R 13', 'material' => 'Papyrus'),
  array('id' => 706, 'title' => 'M.P.E.R 15', 'material' => 'Papyrus'),
  array('id' => 707, 'title' => 'M.P.E.R 17', 'material' => 'Papyrus'),
  array('id' => 708, 'title' => 'M.P.E.R 18', 'material' => 'Papyrus'),
  array('id' => 710, 'title' => 'Mitteis, Chrest.', 'material' => 'Papyrus'),
  array('id' => 715, 'title' => 'P. Mon. 1', 'material' => 'Papyrus'),
  array('id' => 717, 'title' => 'P. Mon. 3', 'material' => 'Papyrus'),
  array('id' => 718, 'title' => 'P. Mon.Apollo', 'material' => 'Papyrus'),
  array('id' => 719, 'title' => 'P. Mon.Epiph.', 'material' => 'Papyrus'),
  array('id' => 720, 'title' => 'P. Mon.Phoeb.', 'material' => 'Papyrus'),
  array('id' => 730, 'title' => 'P. Nag Hammadi', 'material' => 'Papyrus'),
  array('id' => 732, 'title' => 'P. Naqlun 1', 'material' => 'Papyrus'),
  array('id' => 735, 'title' => 'P. Neph.', 'material' => 'Papyrus'),
  array('id' => 740, 'title' => 'P. New York 1', 'material' => 'Papyrus'),
  array('id' => 741, 'title' => 'P. New York 2', 'material' => 'Papyrus'),
  array('id' => 746, 'title' => 'P. Oslo 2', 'material' => 'Papyrus'),
  array('id' => 747, 'title' => 'P. Oslo 3', 'material' => 'Papyrus'),
  array('id' => 750, 'title' => 'P. Oxy. 1', 'material' => 'Papyrus'),
  array('id' => 751, 'title' => 'P. Oxy. 2', 'material' => 'Papyrus'),
  array('id' => 752, 'title' => 'P. Oxy. 3', 'material' => 'Papyrus'),
  array('id' => 753, 'title' => 'P. Oxy. 4', 'material' => 'Papyrus'),
  array('id' => 754, 'title' => 'P. Oxy. 6', 'material' => 'Papyrus'),
  array('id' => 755, 'title' => 'P. Oxy. 7', 'material' => 'Papyrus'),
  array('id' => 756, 'title' => 'P. Oxy. 8', 'material' => 'Papyrus'),
  array('id' => 757, 'title' => 'P. Oxy. 9', 'material' => 'Papyrus'),
  array('id' => 758, 'title' => 'P. Oxy. 10', 'material' => 'Papyrus'),
  array('id' => 759, 'title' => 'P. Oxy. 12', 'material' => 'Papyrus'),
  array('id' => 760, 'title' => 'P. Oxy. 14', 'material' => 'Papyrus'),
  array('id' => 761, 'title' => 'P. Oxy. 16', 'material' => 'Papyrus'),
  array('id' => 762, 'title' => 'P. Oxy. 17', 'material' => 'Papyrus'),
  array('id' => 763, 'title' => 'P. Oxy. 18', 'material' => 'Papyrus'),
  array('id' => 764, 'title' => 'P. Oxy. 19', 'material' => 'Papyrus'),
  array('id' => 765, 'title' => 'P. Oxy. 20', 'material' => 'Papyrus'),
  array('id' => 766, 'title' => 'P. Oxy. 22', 'material' => 'Papyrus'),
  array('id' => 767, 'title' => 'P. Oxy. 24', 'material' => 'Papyrus'),
  array('id' => 768, 'title' => 'P. Oxy. 25', 'material' => 'Papyrus'),
  array('id' => 769, 'title' => 'P. Oxy. 27', 'material' => 'Papyrus'),
  array('id' => 770, 'title' => 'P. Oxy. 31', 'material' => 'Papyrus'),
  array('id' => 771, 'title' => 'P. Oxy. 33', 'material' => 'Papyrus'),
  array('id' => 772, 'title' => 'P. Oxy. 34', 'material' => 'Papyrus'),
  array('id' => 773, 'title' => 'P. Oxy. 36', 'material' => 'Papyrus'),
  array('id' => 774, 'title' => 'P. Oxy. 38', 'material' => 'Papyrus'),
  array('id' => 775, 'title' => 'P. Oxy. 40', 'material' => 'Papyrus'),
  array('id' => 776, 'title' => 'P. Oxy. 41', 'material' => 'Papyrus'),
  array('id' => 777, 'title' => 'P. Oxy. 42', 'material' => 'Papyrus'),
  array('id' => 778, 'title' => 'P. Oxy. 43', 'material' => 'Papyrus'),
  array('id' => 779, 'title' => 'P. Oxy. 44', 'material' => 'Papyrus'),
  array('id' => 780, 'title' => 'P. Oxy. 45', 'material' => 'Papyrus'),
  array('id' => 781, 'title' => 'P. Oxy. 46', 'material' => 'Papyrus'),
  array('id' => 782, 'title' => 'P. Oxy. 47', 'material' => 'Papyrus'),
  array('id' => 783, 'title' => 'P. Oxy. 48', 'material' => 'Papyrus'),
  array('id' => 784, 'title' => 'P. Oxy. 49', 'material' => 'Papyrus'),
  array('id' => 785, 'title' => 'P. Oxy. 50', 'material' => 'Papyrus'),
  array('id' => 786, 'title' => 'P. Oxy. 51', 'material' => 'Papyrus'),
  array('id' => 787, 'title' => 'P. Oxy. 52', 'material' => 'Papyrus'),
  array('id' => 788, 'title' => 'P. Oxy. 54', 'material' => 'Papyrus'),
  array('id' => 789, 'title' => 'P. Oxy. 55', 'material' => 'Papyrus'),
  array('id' => 790, 'title' => 'P. Oxy. 56', 'material' => 'Papyrus'),
  array('id' => 791, 'title' => 'P. Oxy. 57', 'material' => 'Papyrus'),
  array('id' => 792, 'title' => 'P. Oxy. 58', 'material' => 'Papyrus'),
  array('id' => 793, 'title' => 'P. Oxy. 59', 'material' => 'Papyrus'),
  array('id' => 794, 'title' => 'P. Oxy. 60', 'material' => 'Papyrus'),
  array('id' => 794, 'title' => 'P. Oxy. 61', 'material' => 'Papyrus', 'idNew' => 794001),
  array('id' => 795, 'title' => 'P. Oxy. 62', 'material' => 'Papyrus'),
  array('id' => 796, 'title' => 'P. Oxy. 63', 'material' => 'Papyrus'),
  array('id' => 797, 'title' => 'P. Oxy. 64', 'material' => 'Papyrus'),
  array('id' => 798, 'title' => 'P. Oxy. 65', 'material' => 'Papyrus'),
  array('id' => 799, 'title' => 'P. Oxy. 66', 'material' => 'Papyrus'),
  array('id' => 800, 'title' => 'P. Oxy. 67', 'material' => 'Papyrus'),
  array('id' => 809, 'title' => 'P. Oxy.Census', 'material' => 'Papyrus'),
  array('id' => 810, 'title' => 'P. Oxy.Hels.', 'material' => 'Papyrus'),
  array('id' => 812, 'title' => 'P. Palau Rib.', 'material' => 'Papyrus'),
  array('id' => 815, 'title' => 'P. Panop.', 'material' => 'Papyrus'),
  array('id' => 820, 'title' => 'P. Panop.Borkowski', 'material' => 'Papyrus'),
  array('id' => 825, 'title' => 'P. Par.', 'material' => 'Papyrus'),
  array('id' => 830, 'title' => 'P. Petaüs', 'material' => 'Papyrus'),
  array('id' => 832, 'title' => 'P. Petra', 'material' => 'Papyrus'),
  array('id' => 835, 'title' => 'P. Petr. 1', 'material' => 'Papyrus'),
  array('id' => 836, 'title' => 'P. Petr. 2', 'material' => 'Papyrus'),
  array('id' => 837, 'title' => 'P. Petr. 3', 'material' => 'Papyrus'),
  array('id' => 838, 'title' => 'P. Petr. (2. Aufl.) 1', 'material' => 'Papyrus'),
  array('id' => 839, 'title' => 'P. Pher.', 'material' => 'Papyrus'),
  array('id' => 840, 'title' => 'P. Phil.', 'material' => 'Papyrus'),
  array('id' => 842, 'title' => 'P. Polit. lud.', 'material' => 'Papyrus'),
  array('id' => 843, 'title' => 'P. Pommersf.', 'material' => 'Papyrus'),
  array('id' => 845, 'title' => 'P. Prag. 1', 'material' => 'Papyrus'),
  array('id' => 846, 'title' => 'P. Prag. 2', 'material' => 'Papyrus'),
  array('id' => 855, 'title' => 'P. Princ.Univ. 1', 'material' => 'Papyrus'),
  array('id' => 856, 'title' => 'P. Princ.Univ. 2', 'material' => 'Papyrus'),
  array('id' => 857, 'title' => 'P. Princ.Univ. 3', 'material' => 'Papyrus'),
  array('id' => 860, 'title' => 'P. Rainer Cent.', 'material' => 'Papyrus'),
  array('id' => 865, 'title' => 'Recueil 1', 'material' => 'Papyrus'),
  array('id' => 866, 'title' => 'Recueil 2', 'material' => 'Papyrus'),
  array('id' => 870, 'title' => 'P. Rein. 1', 'material' => 'Papyrus'),
  array('id' => 871, 'title' => 'P. Rein. 2', 'material' => 'Papyrus'),
  array('id' => 875, 'title' => 'Rev.Laws', 'material' => 'Papyrus'),
  array('id' => 880, 'title' => 'P. Ross.-Georg. 1', 'material' => 'Papyrus'),
  array('id' => 881, 'title' => 'P. Ross.-Georg. 2', 'material' => 'Papyrus'),
  array('id' => 882, 'title' => 'P. Ross.-Georg. 3', 'material' => 'Papyrus'),
  array('id' => 883, 'title' => 'P. Ross.-Georg. 4', 'material' => 'Papyrus'),
  array('id' => 884, 'title' => 'P. Ross.-Georg. 5', 'material' => 'Papyrus'),
  array('id' => 890, 'title' => 'P. Ryl. 1', 'material' => 'Papyrus'),
  array('id' => 891, 'title' => 'P. Ryl. 2', 'material' => 'Papyrus'),
  array('id' => 892, 'title' => 'P. Ryl. 3', 'material' => 'Papyrus'),
  array('id' => 893, 'title' => 'P. Ryl. 4', 'material' => 'Papyrus'),
  array('id' => 900, 'title' => 'P. Sakaon', 'material' => 'Papyrus'),
  array('id' => 905, 'title' => 'S.B. 1', 'material' => 'Papyrus'),
  array('id' => 906, 'title' => 'S.B. 3', 'material' => 'Papyrus'),
  array('id' => 907, 'title' => 'S.B. 4', 'material' => 'Papyrus'),
  array('id' => 908, 'title' => 'S.B. 5', 'material' => 'Papyrus'),
  array('id' => 909, 'title' => 'S.B. 6', 'material' => 'Papyrus'),
  array('id' => 910, 'title' => 'S.B. 8', 'material' => 'Papyrus'),
  array('id' => 911, 'title' => 'S.B. 10', 'material' => 'Papyrus'),
  array('id' => 912, 'title' => 'S.B. 12', 'material' => 'Papyrus'),
  array('id' => 913, 'title' => 'S.B. 14', 'material' => 'Papyrus'),
  array('id' => 914, 'title' => 'S.B. 16', 'material' => 'Papyrus'),
  array('id' => 915, 'title' => 'S.B. 18', 'material' => 'Papyrus'),
  array('id' => 916, 'title' => 'S.B. 20', 'material' => 'Papyrus'),
  array('id' => 917, 'title' => 'S.B. 22', 'material' => 'Papyrus'),
  array('id' => 918, 'title' => 'S.B. 24', 'material' => 'Papyrus'),
  array('id' => 919, 'title' => 'S.B. 26', 'material' => 'Papyrus'),
  array('id' => 935, 'title' => 'P. Sarap.', 'material' => 'Papyrus'),
  array('id' => 935, 'title' => 'P. Sijp.', 'material' => 'Papyrus', 'idNew' => 935100),
  array('id' => 940, 'title' => 'P. S.A.Athen.', 'material' => 'Papyrus'),
  array('id' => 945, 'title' => 'P. Soc. 1', 'material' => 'Papyrus'),
  array('id' => 946, 'title' => 'P. Soc. 2', 'material' => 'Papyrus'),
  array('id' => 947, 'title' => 'P. Soc. 3', 'material' => 'Papyrus'),
  array('id' => 948, 'title' => 'P. Soc. 4', 'material' => 'Papyrus'),
  array('id' => 949, 'title' => 'P. Soc. 5', 'material' => 'Papyrus'),
  array('id' => 950, 'title' => 'P. Soc. 6', 'material' => 'Papyrus'),
  array('id' => 951, 'title' => 'P. Soc. 7', 'material' => 'Papyrus'),
  array('id' => 952, 'title' => 'P. Soc. 8', 'material' => 'Papyrus'),
  array('id' => 953, 'title' => 'P. Soc. 9', 'material' => 'Papyrus'),
  array('id' => 954, 'title' => 'P. Soc. 10', 'material' => 'Papyrus'),
  array('id' => 955, 'title' => 'P. Soc. 11', 'material' => 'Papyrus'),
  array('id' => 956, 'title' => 'P. Soc. 12', 'material' => 'Papyrus'),
  array('id' => 957, 'title' => 'P. Soc. 13', 'material' => 'Papyrus'),
  array('id' => 958, 'title' => 'P. Soc. 14', 'material' => 'Papyrus'),
  array('id' => 959, 'title' => 'P. Soc. 15', 'material' => 'Papyrus'),
  array('id' => 970, 'title' => 'P. Soc. XI Congr.', 'material' => 'Papyrus'),
  array('id' => 975, 'title' => 'P. Soc. XVII Congr.', 'material' => 'Papyrus'),
  array('id' => 976, 'title' => 'P. Soc. XX Congr.', 'material' => 'Papyrus'),
  array('id' => 977, 'title' => 'P. Soc. XXI Congr.', 'material' => 'Papyrus'),
  array('id' => 985, 'title' => 'P. Sorb. 1', 'material' => 'Papyrus'),
  array('id' => 986, 'title' => 'P. Sorb. 2 (69)', 'material' => 'Papyrus'),
  array('id' => 990, 'title' => 'P. Soterichos', 'material' => 'Papyrus'),
  array('id' => 993, 'title' => 'P. Sta.Xyla', 'material' => 'Papyrus'),
  array('id' => 995, 'title' => 'P. Strasb. 1', 'material' => 'Papyrus'),
  array('id' => 996, 'title' => 'P. Strasb. 2', 'material' => 'Papyrus'),
  array('id' => 997, 'title' => 'P. Strasb. 3', 'material' => 'Papyrus'),
  array('id' => 998, 'title' => 'P. Strasb. 4', 'material' => 'Papyrus'),
  array('id' => 999, 'title' => 'P. Strasb. 5', 'material' => 'Papyrus'),
  array('id' => 1000, 'title' => 'P. Strasb. 6', 'material' => 'Papyrus'),
  array('id' => 1001, 'title' => 'P. Strasb. 7', 'material' => 'Papyrus'),
  array('id' => 1002, 'title' => 'P. Strasb. 8', 'material' => 'Papyrus'),
  array('id' => 1003, 'title' => 'P. Strasb. 9', 'material' => 'Papyrus'),
  array('id' => 1015, 'title' => 'Stud.Pal. 1', 'material' => 'Papyrus'),
  array('id' => 1016, 'title' => 'Stud.Pal. 2', 'material' => 'Papyrus'),
  array('id' => 1017, 'title' => 'Stud.Pal. 3', 'material' => 'Papyrus'),
  array('id' => 1018, 'title' => 'Stud.Pal. 4', 'material' => 'Papyrus'),
  array('id' => 1019, 'title' => 'Stud.Pal. 5', 'material' => 'Papyrus'),
  array('id' => 1020, 'title' => 'Stud.Pal. 8', 'material' => 'Papyrus'),
  array('id' => 1021, 'title' => 'Stud.Pal. 10', 'material' => 'Papyrus'),
  array('id' => 1022, 'title' => 'Stud.Pal. 13', 'material' => 'Papyrus'),
  array('id' => 1023, 'title' => 'Stud.Pal. 14', 'material' => 'Papyrus'),
  array('id' => 1024, 'title' => 'Stud.Pal. 17', 'material' => 'Papyrus'),
  array('id' => 1025, 'title' => 'Stud.Pal. 20', 'material' => 'Papyrus'),
  array('id' => 1026, 'title' => 'Stud.Pal. 22', 'material' => 'Papyrus'),
  array('id' => 1027, 'title' => 'Stud.Pal. 23 Teil 1', 'material' => 'Papyrus'),
  array('id' => 1028, 'title' => 'Stud.Pal. 23 Teil 2', 'material' => 'Papyrus'),
  array('id' => 1030, 'title' => 'P. Tebt. 1', 'material' => 'Papyrus'),
  array('id' => 1031, 'title' => 'P. Tebt. 2', 'material' => 'Papyrus'),
  array('id' => 1032, 'title' => 'P. Tebt. 3 Teil 1', 'material' => 'Papyrus'),
  array('id' => 1033, 'title' => 'P. Tebt. 3 Teil 2', 'material' => 'Papyrus'),
  array('id' => 1034, 'title' => 'P. Tebt. 4', 'material' => 'Papyrus'),
  array('id' => 1040, 'title' => 'P. Tebt.Tait', 'material' => 'Papyrus'),
  array('id' => 1050, 'title' => 'P. Theones', 'material' => 'Papyrus'),
  array('id' => 1055, 'title' => 'P. Thmouis 1', 'material' => 'Papyrus'),
  array('id' => 1058, 'title' => 'P. Thomas', 'material' => 'Papyrus'),
  array('id' => 1060, 'title' => 'P. Tor.Amenothes', 'material' => 'Papyrus'),
  array('id' => 1061, 'title' => 'P. Tor.Choachiti', 'material' => 'Papyrus'),
  array('id' => 1065, 'title' => 'P. Turin', 'material' => 'Papyrus'),
  array('id' => 1070, 'title' => 'P. Turner', 'material' => 'Papyrus'),
  array('id' => 1075, 'title' => 'P.U.G. 1', 'material' => 'Papyrus'),
  array('id' => 1076, 'title' => 'P.U.G. 2', 'material' => 'Papyrus'),
  array('id' => 1077, 'title' => 'P.U.G. 3', 'material' => 'Papyrus'),
  array('id' => 1080, 'title' => 'P. Ups. 8', 'material' => 'Papyrus'),
  array('id' => 1085, 'title' => 'P. Ups.Frid.', 'material' => 'Papyrus'),
  array('id' => 1090, 'title' => 'U.P.Z. 1', 'material' => 'Papyrus'),
  array('id' => 1091, 'title' => 'U.P.Z. 2', 'material' => 'Papyrus'),
  array('id' => 1095, 'title' => 'P. Vars.', 'material' => 'Papyrus'),
  array('id' => 1100, 'title' => 'P. Vatic.Aphr.', 'material' => 'Papyrus'),
  array('id' => 1105, 'title' => 'P. Vindob.Salomons', 'material' => 'Papyrus'),
  array('id' => 1110, 'title' => 'P. Vindob.Tandem', 'material' => 'Papyrus'),
  array('id' => 1115, 'title' => 'P. Vindob.Worp', 'material' => 'Papyrus'),
  array('id' => 1120, 'title' => 'P. Wash.Univ. 1', 'material' => 'Papyrus'),
  array('id' => 1121, 'title' => 'P. Wash.Univ. 2', 'material' => 'Papyrus'),
  array('id' => 1125, 'title' => 'Wilcken, Chrest.', 'material' => 'Papyrus'),
  array('id' => 1135, 'title' => 'P. Wisc. 2', 'material' => 'Papyrus'),
  array('id' => 1140, 'title' => 'P. Würzb.', 'material' => 'Papyrus'),
  array('id' => 1143, 'title' => 'P. Yadin', 'material' => 'Papyrus'),
  array('id' => 1144, 'title' => 'P. Yadin 2', 'material' => 'Papyrus'),
  array('id' => 1145, 'title' => 'P. Yale 1', 'material' => 'Papyrus'),
  array('id' => 1146, 'title' => 'P. Yale 2', 'material' => 'Papyrus'),
  array('id' => 1147, 'title' => 'P. Yale 3', 'material' => 'Papyrus'),
  array('id' => 1150, 'title' => 'O. Aberd.', 'material' => 'Ostrakon'),
  array('id' => 1155, 'title' => 'O. Amst.', 'material' => 'Ostrakon'),
  array('id' => 1158, 'title' => 'O. Ashm.Shelton', 'material' => 'Ostrakon'),
  array('id' => 1160, 'title' => 'O. Baden 4', 'material' => 'Ostrakon'),
  array('id' => 1162, 'title' => 'O. Berenike 1', 'material' => 'Ostrakon'),
  array('id' => 1165, 'title' => 'O. Brüss.-Berl.', 'material' => 'Ostrakon'),
  array('id' => 1166, 'title' => 'O. Cairo Cat.', 'material' => 'Ostrakon'),
  array('id' => 1167, 'title' => 'O. Cairo G.P.W.', 'material' => 'Ostrakon'),
  array('id' => 1168, 'title' => 'O. Claud. 1', 'material' => 'Ostrakon'),
  array('id' => 1169, 'title' => 'O. Claud. 2', 'material' => 'Ostrakon'),
  array('id' => 1169, 'title' => 'O. Claud. 3', 'material' => 'Ostrakon', 'idNew' => 1169001),
  array('id' => 1170, 'title' => 'O. Douch 1', 'material' => 'Ostrakon'),
  array('id' => 1171, 'title' => 'O. Douch 2', 'material' => 'Ostrakon'),
  array('id' => 1172, 'title' => 'O. Douch 3', 'material' => 'Ostrakon'),
  array('id' => 1173, 'title' => 'O. Douch 4', 'material' => 'Ostrakon'),
  array('id' => 1174, 'title' => 'O. Douch 5', 'material' => 'Ostrakon'),
  array('id' => 1175, 'title' => 'O. Edfou 1', 'material' => 'Ostrakon'),
  array('id' => 1176, 'title' => 'O. Edfou 2', 'material' => 'Ostrakon'),
  array('id' => 1177, 'title' => 'O. Edfou 3', 'material' => 'Ostrakon'),
  array('id' => 1178, 'title' => 'O. Eleph.D.A.I.K.', 'material' => 'Ostrakon'),
  array('id' => 1179, 'title' => 'O. Elkab gr.', 'material' => 'Ostrakon'),
  array('id' => 1180, 'title' => 'O. Fay.', 'material' => 'Ostrakon'),
  array('id' => 1185, 'title' => 'O. Florida', 'material' => 'Ostrakon'),
  array('id' => 1190, 'title' => 'O. Heid. 3', 'material' => 'Ostrakon'),
  array('id' => 1193, 'title' => 'O. Joachim', 'material' => 'Ostrakon'),
  array('id' => 1195, 'title' => 'O. Krok. 1', 'material' => 'Ostrakon'),
  array('id' => 1200, 'title' => 'O. Leid.', 'material' => 'Ostrakon'),
  array('id' => 1205, 'title' => 'O. Lund.', 'material' => 'Ostrakon'),
  array('id' => 1210, 'title' => 'O. Medinet Madi', 'material' => 'Ostrakon'),
  array('id' => 1215, 'title' => 'O. Meyer', 'material' => 'Ostrakon'),
  array('id' => 1220, 'title' => 'O. Mich. 1', 'material' => 'Ostrakon'),
  array('id' => 1221, 'title' => 'O. Mich. 2', 'material' => 'Ostrakon'),
  array('id' => 1222, 'title' => 'O. Mich. 3', 'material' => 'Ostrakon'),
  array('id' => 1223, 'title' => 'O. Dem.Narmuthis 1', 'material' => 'Ostrakon'),
  array('id' => 1224, 'title' => 'O. Gr.Narmuthis 1', 'material' => 'Ostrakon'),
  array('id' => 1225, 'title' => 'O. Ont.Mus. 1', 'material' => 'Ostrakon'),
  array('id' => 1226, 'title' => 'O. Ont.Mus. 2', 'material' => 'Ostrakon'),
  array('id' => 1230, 'title' => 'O. Oslo', 'material' => 'Ostrakon'),
  array('id' => 1240, 'title' => 'O. Soc. 3', 'material' => 'Ostrakon'),
  array('id' => 1241, 'title' => 'O. Soc. 8', 'material' => 'Ostrakon'),
  array('id' => 1245, 'title' => 'O. Strasb.', 'material' => 'Ostrakon'),
  array('id' => 1250, 'title' => 'O. Tait 1', 'material' => 'Ostrakon'),
  array('id' => 1251, 'title' => 'O. Tait 2', 'material' => 'Ostrakon'),
  array('id' => 1255, 'title' => 'O. Tebt.Pad. 1', 'material' => 'Ostrakon'),
  array('id' => 1260, 'title' => 'O. Theb.', 'material' => 'Ostrakon'),
  array('id' => 1262, 'title' => 'O. Waqfa', 'material' => 'Ostrakon'),
  array('id' => 1265, 'title' => 'O. Wilb.-Brk.', 'material' => 'Ostrakon'),
  array('id' => 1270, 'title' => 'O. Wilcken 1', 'material' => 'Ostrakon'),
  array('id' => 1271, 'title' => 'O. Wilcken 2', 'material' => 'Ostrakon'),
  array('id' => 1300, 'title' => 'Tavolette Varie', 'material' => 'Ostrakon')
);

    function load(ObjectManager $manager)
    {
        $editions = array();
          
        foreach(self::$EDITIONS as $edition){
          $e = new Edition();
          $e->setSort(isset($edition['idNew']) ? ($edition['idNew'] . '') : (($edition['id'] * 1000) . ''));
          $e->setTitle($edition['title']);
          $e->setMaterial($edition['material']);

          $this->addReference('edition_' . $e->getTitle(), $e);

          $manager->persist($e);
        }

        $manager->flush();

    }

    public function getOrder()
    {
        return 1;
    }
}
?>