security:
    encoders:
        Papyrillio\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            providers: [user_db]
        user_db:
            entity: { class: Papyrillio\UserBundle\Entity\User, property: username }


    firewalls:
        #dev:
            #pattern:  ^/(_(profiler|wdt)|css|images|js)/
            #security: true

        #login:
            #pattern:  ^/login
            #security: false

        login_firewall:
            pattern:    ^/login$
            anonymous:  ~

        secured_area:
            pattern:    ^/
            #anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
                #use_referer: true
                always_use_default_target_path: true
                #default_target_path: PapyrillioBeehiveBundle_home
                default_target_path: PapyrillioUserBundle_tadaima
            logout:
                path:   /logout
                target: /login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: ROLE_USER}        
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
