PapyrillioBeehiveBundle_about:
    pattern:  /about
    defaults: { _controller: PapyrillioBeehiveBundle:Default:about }

PapyrillioBeehiveBundle_contact:
    pattern:  /contact
    defaults: { _controller: PapyrillioBeehiveBundle:Default:contact }

PapyrillioBeehiveBundle_help:
    pattern:  /help
    defaults: { _controller: PapyrillioBeehiveBundle:Default:help }

PapyrillioBeehiveBundle_home:
    pattern:  /
    defaults: { _controller: PapyrillioBeehiveBundle:Default:index }

PapyrillioBeehiveBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PapyrillioBeehiveBundle:Default:index }

# NumberWizard

PapyrillioBeehiveBundle_numberwizard:
    pattern:  /numberWizard
    defaults: { _controller: PapyrillioBeehiveBundle:NumberWizard:index}

PapyrillioBeehiveBundle_numberwizardlookup:
    pattern:  /numberWizard/lookup
    defaults: { _controller: PapyrillioBeehiveBundle:NumberWizard:lookup}

PapyrillioBeehiveBundle_numberwizardautocompleteddb:
    pattern:  /numberWizard/autocomplete/ddb
    defaults: { _controller: PapyrillioBeehiveBundle:NumberWizard:autocompleteDdb}

# Register

PapyrillioBeehiveBundle_registershow:
    pattern:  /register/show/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Register:show }
    requirements:
      id: '\d+'

PapyrillioBeehiveBundle_registerautocomplete:
    pattern:  /register/autocomplete/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Register:autocomplete, id = 0}

PapyrillioBeehiveBundle_registerautocompleteddb:
    pattern:  /register/autocompleteDdb
    defaults: { _controller: PapyrillioBeehiveBundle:Register:autocompleteDdb}

PapyrillioBeehiveBundle_registershowassignments:
    pattern:  /register/showAssignments/{correctionId}
    defaults: { _controller: PapyrillioBeehiveBundle:Register:showAssignments}
    requirements:
      correctionId: '\d+'

PapyrillioBeehiveBundle_registerrevokeassignment:
    pattern:  /register/revokeAssignment/{registerId}/{correctionId}
    defaults: { _controller: PapyrillioBeehiveBundle:Register:revokeAssignment}
    requirements:
      registerId: '\d+'
      correctionId: '\d+'

PapyrillioBeehiveBundle_registerassign:
    pattern:  /register/assign/{registerId}/{correctionId}
    defaults: { _controller: PapyrillioBeehiveBundle:Register:assign}
    requirements:
      registerId: '\d+'
      correctionId: '\d+'

PapyrillioBeehiveBundle_registercreate:
    pattern:  /register/create
    defaults: { _controller: PapyrillioBeehiveBundle:Register:create}

PapyrillioBeehiveBundle_registercreateandassign:
    pattern:  /register/createAndAssign/{correctionId}
    defaults: { _controller: PapyrillioBeehiveBundle:Register:createAndAssign}
    requirements:
      correctionId: '\d+'

PapyrillioBeehiveBundle_registerwizard:
    pattern:  /registerWizard/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Register:wizard}
    requirements:
      correctionId: '\d+'

PapyrillioBeehiveBundle_registerapiary:
    pattern:  /registerApiary/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Register:apiary}
    requirements:
      correctionId: '\d+'

# Report

PapyrillioBeehiveBundle_report:
    pattern:  /report
    defaults: { _controller: PapyrillioBeehiveBundle:Report:leiden, compilationVolume: 13 }

PapyrillioBeehiveBundle_reportleiden:
    pattern:  /report/leiden/{compilationVolume}
    defaults: { _controller: PapyrillioBeehiveBundle:Report:leiden, compilationVolume: 13 }

PapyrillioBeehiveBundle_reportsnippet:
    pattern:  /report/snippet/leiden/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Report:leidenSnippet }

PapyrillioBeehiveBundle_reportoverview:
    pattern:  /report/overview/{compilationVolume}
    defaults: { _controller: PapyrillioBeehiveBundle:Report:overview, compilationVolume: 13 }

PapyrillioBeehiveBundle_reportprint:
    pattern:  /report/print/{compilationVolume}/{editionId}
    defaults: { _controller: PapyrillioBeehiveBundle:Report:print, compilationVolume: 13, editionId: 0 }

PapyrillioBeehiveBundle_reportpdf:
    pattern:  /report/pdf/{compilationVolume}/{editionId}
    defaults: { _controller: PapyrillioBeehiveBundle:Report:pdf, compilationVolume: 13, editionId: 0 }

# Correction

PapyrillioBeehiveBundle_correctionlist:
    pattern:  /correction/list
    defaults: { _controller: PapyrillioBeehiveBundle:Correction:list }

PapyrillioBeehiveBundle_correctionprint:
    pattern:  /correction/print
    defaults: { _controller: PapyrillioBeehiveBundle:Correction:list, print: true}

PapyrillioBeehiveBundle_correctionshow:
    pattern:  /correction/show/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Correction:show }

PapyrillioBeehiveBundle_correctiontest:
    pattern:  /correction/test/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Correction:test }

PapyrillioBeehiveBundle_correctiondelete:
    pattern:  /correction/delete/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Correction:delete }

PapyrillioBeehiveBundle_correctionnew:
    pattern:  /correction/new
    defaults: { _controller: PapyrillioBeehiveBundle:Correction:new }

PapyrillioBeehiveBundle_correctionupdate:
    pattern:  /correction/update/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Correction:update }

PapyrillioBeehiveBundle_correctionlinksnippet:
    pattern:  /correction/snippet/link/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Correction:snippetLink }

# Edition

PapyrillioBeehiveBundle_editionlist:
    pattern:  /edition/list
    defaults: { _controller: PapyrillioBeehiveBundle:Edition:list }

PapyrillioBeehiveBundle_editionshow:
    pattern:  /edition/show/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Edition:show }

PapyrillioBeehiveBundle_editiondelete:
    pattern:  /edition/delete/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Edition:delete }

PapyrillioBeehiveBundle_editionnew:
    pattern:  /edition/new
    defaults: { _controller: PapyrillioBeehiveBundle:Edition:new }

PapyrillioBeehiveBundle_editionupdate:
    pattern:  /edition/update
    defaults: { _controller: PapyrillioBeehiveBundle:Edition:update }

# Task

PapyrillioBeehiveBundle_taskdelete:
    pattern:  /task/delete/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Task:delete }

PapyrillioBeehiveBundle_tasksnippet:
    pattern:  /task/snippet/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Task:snippet }

PapyrillioBeehiveBundle_tasknew:
    pattern:  /task/new
    defaults: { _controller: PapyrillioBeehiveBundle:Task:new }

PapyrillioBeehiveBundle_taskupdate:
    pattern:  /task/update/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Task:update }

# Index

PapyrillioBeehiveBundle_indexdelete:
    pattern:  /index/delete/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Index:delete }

PapyrillioBeehiveBundle_indexsnippet:
    pattern:  /index/snippet/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Index:snippet }

PapyrillioBeehiveBundle_indexnew:
    pattern:  /index/new
    defaults: { _controller: PapyrillioBeehiveBundle:Index:new }

PapyrillioBeehiveBundle_indexupdate:
    pattern:  /index/update/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Index:update }

# System

PapyrillioBeehiveBundle_systemsort:
    pattern:  /system/sort/{editionId}
    defaults: { _controller: PapyrillioBeehiveBundle:System:sort, editionId: 0 }

PapyrillioBeehiveBundle_systemchecksort:
    pattern:  /system/checkSort/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:System:checkSort }

# Apiary

PapyrillioBeehiveBundle_apiary:
    pattern:  /browse
    defaults: { _controller: PapyrillioBeehiveBundle:Apiary:index, format: html}


PapyrillioBeehiveBundle_apiaryhoney:
    pattern:  /{type}/{id}/{format}
    defaults: { _controller: PapyrillioBeehiveBundle:Apiary:honey, format: html}
    requirements:
      type: '(tm|hgv|ddb|biblio|bl|register)'