PapyrillioBeehiveBundle_about:
    pattern:  /about
    defaults: { _controller: PapyrillioBeehiveBundle:Default:about }

PapyrillioBeehiveBundle_contact:
    pattern:  /contact
    defaults: { _controller: PapyrillioBeehiveBundle:Default:contact }

PapyrillioBeehiveBundle_help:
    pattern:  /help
    defaults: { _controller: PapyrillioBeehiveBundle:Default:help }

PapyrillioBeehiveBundle_home:
    pattern:  /
    defaults: { _controller: PapyrillioBeehiveBundle:Default:index }

PapyrillioBeehiveBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PapyrillioBeehiveBundle:Default:index }

# Correction

PapyrillioBeehiveBundle_report:
    pattern:  /report
    defaults: { _controller: PapyrillioBeehiveBundle:Report:leiden, compilationVolume: 13 }

PapyrillioBeehiveBundle_reportleiden:
    pattern:  /report/leiden/{compilationVolume}
    defaults: { _controller: PapyrillioBeehiveBundle:Report:leiden, compilationVolume: 13 }

PapyrillioBeehiveBundle_correctionlist:
    pattern:  /correction/list
    defaults: { _controller: PapyrillioBeehiveBundle:Correction:list }

PapyrillioBeehiveBundle_correctionshow:
    pattern:  /correction/show/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Correction:show }

PapyrillioBeehiveBundle_correctiondelete:
    pattern:  /correction/delete/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Correction:delete }

PapyrillioBeehiveBundle_correctionnew:
    pattern:  /correction/new
    defaults: { _controller: PapyrillioBeehiveBundle:Correction:new }

PapyrillioBeehiveBundle_correctionupdate:
    pattern:  /correction/update/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Correction:update }

# Edition

PapyrillioBeehiveBundle_editionlist:
    pattern:  /edition/list
    defaults: { _controller: PapyrillioBeehiveBundle:Edition:list }

PapyrillioBeehiveBundle_editionshow:
    pattern:  /edition/show/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Edition:show }

PapyrillioBeehiveBundle_editiondelete:
    pattern:  /edition/delete/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Edition:delete }

PapyrillioBeehiveBundle_editionnew:
    pattern:  /edition/new
    defaults: { _controller: PapyrillioBeehiveBundle:Edition:new }

PapyrillioBeehiveBundle_editionupdate:
    pattern:  /edition/update/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Edition:update }

# Task

PapyrillioBeehiveBundle_taskupdate:
    pattern:  /task/update/{id}
    defaults: { _controller: PapyrillioBeehiveBundle:Task:update }
