Papyrillio\BeehiveBundle\Entity\Correction:
    message: 'Ungültige Eingabe'
    properties:
        bl:
            - NotBlank:
                message: 'Editionsnummern sind rein numerisch wie z.B. »175«'
            - Regex:
                pattern: '/^\d+$/'
                message: 'Editionsnummern sind rein numerisch wie z.B. »175«'
        edition:
            - NotBlank:
                message: 'Editionsnamen sind als Freitext einzugeben wie z.B. »P. Cairo Masp. 1«'
            - MinLength:
                limit: 3
                message: 'Editionsnamen sind als Freitext einzugeben wie z.B. »P. Cairo Masp. 1«'
        text:
            - NotBlank:
                message: 'Textbezeichner sind als Freitext einzugeben wie z.B. »16 (auf S. 17)«'
        tm:
            - NotBlank:
                message: 'TM-Nummern sind rein numerisch wie z.B. »9183«'
            - Regex:
                pattern: '/^\d+$/'
                message: 'TM-Nummern sind rein numerisch wie z.B. »9183«'
        hgv:
            - NotBlank:
                message: 'HGV-Ids dürfen nur aus der TM-Nummer gefolgt von einem Kleinbuchstaben zur Kennzeichnung des Textschnipsels bestehen wie z.B. »9183a«'
            - Regex:
                pattern: '/^\d+[a-z]*$/'
                message: 'HGV-Ids dürfen nur aus der TM-Nummer gefolgt von einem Kleinbuchstaben zur Kennzeichnung des Textschnipsels bestehen wie z.B. »9183a«'
        ddb:
            - NotBlank:
                message: 'Bl Ids sind rein numerisch wie z.B. »bgu;2;452«'
            - Regex:
                pattern: '/^[^;]+;[^;]*;[^;]+$/'
                message: 'Bl Ids sind rein numerisch wie z.B. »bgu;2;452«'
        description:
            - NotBlank:
                message: 'Bitte Beschreibung der Berichtigung angeben (Freitext).'
            - MinLength:
                limit: 3
                message: 'Bitte Beschreibung der Berichtigung angeben (Freitext).'