Papyrillio\BeehiveBundle\Entity\Correction:
    message: 'Ungültige Eingabe'
    properties:
        text:
            - NotBlank:
                message: 'Textbezeichner sind als Freitext einzugeben wie z.B. »16 (auf S. 17)«'
        source:
            - Regex:
                pattern: '/^\d+$/'
                message: 'Bitte eine gültige Bilbio-Id eingeben, Bilbio-Ids sind rein numerisch wie z.B. »4066«'
        description:
            - NotBlank:
                message: 'Bitte Beschreibung der Berichtigung angeben (Freitext).'
            - MinLength:
                limit: 3
                message: 'Die Beschreibung muss mindestens 3 Zeichen enthalten.'

Papyrillio\BeehiveBundle\Entity\Edition:
    message: 'Ungültige Eingabe'
    properties:
        sort:
            - NotBlank:
                message: 'Bitte einen numerischen Wert größer 1 zur Sortierung angeben.'
            - Min:
                limit: 1
                message: 'Bitte einen numerischen Wert größer 1 zur Sortierung angeben.'
        title:
            - NotBlank:
                message: 'Bitte den Titel der Edition angeben. Falls eine Bandnummer vorhanden ist, wird diese durch ein Leerzeichen von der Sammlungsbezeichnung getrennt,  wie z.B. »P. Amh. 2«'
        material:
            - NotBlank:
                message: 'Bitte eines der folgenden Materialien auswählen: »Papyrus«, »Ostrakon«'
            - Choice:
                callback: [Papyrillio\BeehiveBundle\Controller\BeehiveController, getEditionMaterials]
                message: 'Bitte eines der folgenden Materialien auswählen: »Papyrus«, »Ostrakon«'

Papyrillio\BeehiveBundle\Entity\Task:
    message: 'Ungültige Eingabe'
    properties:
        category:
            - NotBlank:
                message: 'Bitte eine gültige Aufgaben-Kategorie auswählen: tm, hgv, ddb, biblio, bl oder apis.'
            - Choice:
                callback: [Papyrillio\BeehiveBundle\Controller\BeehiveController, getTaskCategoryKeys]
                message: 'Bitte eine gültige Aufgaben-Kategorie auswählen: tm, hgv, ddb, biblio, bl oder apis.'
        description:
            - NotBlank:
                message: 'Bitte eine Aufgabenbeschreibung angeben.'

Papyrillio\BeehiveBundle\Entity\IndexEntry:
    message: 'Ungültige Eingabe'
    properties:
        phrase:
            - NotBlank:
                message: 'Bitte ein Wort oder eine Phrase angeben.'
        type:
            - Choice:
                callback: [Papyrillio\BeehiveBundle\Controller\BeehiveController, getIndexTypes]
                message: 'Bitte eine gültige Kategorie angeben.'
        topic:
            - Choice:
                callback: [Papyrillio\BeehiveBundle\Controller\BeehiveController, getIndexTopics]
                message: 'Bitte ein gültiges Thema angeben.'