parameters:
#    papyrillio_security.example.class: Papyrillio\SecurityBundle\Example

services:
#    papyrillio_security.example:
#        class: %papyrillio_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
