<?xml version="1.0" encoding="UTF-8"?>

<xsl:stylesheet exclude-result-prefixes="#all" version="2.0"
    xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
    xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0"
    xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"
    xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0"
    xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0"
    xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0"
    xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:meta="urn:oasis:names:tc:opendocument:xmlns:meta:1.0"
    xmlns:number="urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0"
    xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0"
    xmlns:chart="urn:oasis:names:tc:opendocument:xmlns:chart:1.0"
    xmlns:dr3d="urn:oasis:names:tc:opendocument:xmlns:dr3d:1.0"
    xmlns:math="http://www.w3.org/1998/Math/MathML"
    xmlns:form="urn:oasis:names:tc:opendocument:xmlns:form:1.0"
    xmlns:script="urn:oasis:names:tc:opendocument:xmlns:script:1.0"
    xmlns:ooo="http://openoffice.org/2004/office" xmlns:ooow="http://openoffice.org/2004/writer"
    xmlns:oooc="http://openoffice.org/2004/calc" xmlns:dom="http://www.w3.org/2001/xml-events"
    xmlns:xforms="http://www.w3.org/2002/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:rpt="http://openoffice.org/2005/report"
    xmlns:of="urn:oasis:names:tc:opendocument:xmlns:of:1.2"
    xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:grddl="http://www.w3.org/2003/g/data-view#"
    xmlns:officeooo="http://openoffice.org/2009/office"
    xmlns:tableooo="http://openoffice.org/2009/table"
    xmlns:drawooo="http://openoffice.org/2010/draw"
    xmlns:calcext="urn:org:documentfoundation:names:experimental:calc:xmlns:calcext:1.0"
    xmlns:loext="urn:org:documentfoundation:names:experimental:office:xmlns:loext:1.0"
    xmlns:field="urn:openoffice:names:experimental:ooo-ms-interop:xmlns:field:1.0"
    xmlns:formx="urn:openoffice:names:experimental:ooxml-odf-interop:xmlns:form:1.0"
    xmlns:css3t="http://www.w3.org/TR/css3-text/"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:papy="Papyrillio"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:fm="http://www.filemaker.com/fmpxmlresult"
    xmlns:tei="http://www.tei-c.org/ns/1.0"
    xmlns:fn="http://www.xsltfunctions.com/"
    xmlns="http://www.tei-c.org/ns/1.0">

<!--
    java -Xms512m -Xmx1536m net.sf.saxon.Transform -o:content_null.xml -s:content.xml -xsl:makeContentNull.xsl
-->
    <xsl:output method="xml" media-type="text/xml" />
    
    <xsl:variable name="PUBLICATIONS">
        <list>
            <item key="Allgemeines">Allgemeines</item>
            <item key="PAberd">P. Aberd.</item>
            <item key="PAbinn">P. Abinn.</item>
            <item key="PAchmm">P. Achmîm</item>
            <item key="PAdler">P. Adler</item>
            <item key="PAlex">P. Alex.</item>
            <item key="PAlexGiss">P. Alex.Giss.</item>
            <item key="PAmhII">P. Amh. 2</item>
            <item key="PAmmon">P. Ammon</item>
            <item key="PAmstI">P. Amst. 1</item>
            <item key="PAntinI">P. Antin. 1</item>
            <item key="PAntinII">P. Antin. 2</item>
            <item key="PAntinIII">P. Antin. 3</item>
            <item key="PBadenII">P. Baden 2</item>
            <item key="PBadenIV">P. Baden 4</item>
            <item key="PBadenVI">P. Baden 6</item>
            <item key="PBalaizahII">P. Bala’izah 2</item>
            <item key="PBeattyPanop">P. Beatty Panop.</item>
            <item key="BGUI">B.G.U. 1</item>
            <item key="BGUII">B.G.U. 2</item>
            <item key="BGUIII">B.G.U. 3</item>
            <item key="BGUIV">B.G.U. 4</item>
            <item key="BGUV">B.G.U. 5</item>
            <item key="BGUVI">B.G.U. 6</item>
            <item key="BGUVII">B.G.U. 7</item>
            <item key="BGUVIII">B.G.U. 8</item>
            <item key="BGUIX">B.G.U. 9</item>
            <item key="BGUX">B.G.U. 10</item>
            <item key="BGUXI">B.G.U. 11</item>
            <item key="BGUXII">B.G.U. 12</item>
            <item key="BGUXIII">B.G.U. 13</item>
            <item key="BGUXIV">B.G.U. 14</item>
            <item key="BGUXV">B.G.U. 15</item>
            <item key="BGUXVI">B.G.U. 16</item>
            <item key="BGUXVII">B.G.U. 17</item>
            <item key="BGUXVIII">B.G.U. 18</item>
            <item key="BGUXIX">B.G.U. 19</item>
            <item key="PBerlFrisk">P. Berl.Frisk</item>
            <item key="PBerlLeihgI">P. Berl.Leihg. 1</item>
            <item key="PBerlLeihgII">P. Berl.Leihg. 2</item>
            <item key="PBerlMller">P. Berl.Möller</item>
            <item key="PBerlSalmen">P. Berl.Salmen.</item>
            <item key="PBerlZilliacus">P. Berl.Zilliacus</item>
            <item key="PBingen">P. Bingen</item>
            <item key="PBodlI">P. Bodl. 1</item>
            <item key="PBon">P. Bon.</item>
            <item key="PBouriant">P. Bouriant</item>
            <item key="PBrem">P. Brem.</item>
            <item key="PBrooklyn">P. Brooklyn</item>
            <item key="PBubII">P. Bub. 2</item>
            <item key="PCairoGoodspeed">P. Cairo Goodspeed</item>
            <item key="PCairoMaspI">P. Cairo Masp. 1</item>
            <item key="PCairoMaspII">P. Cairo Masp. 2</item>
            <item key="PCairoMaspIII">P. Cairo Masp. 3</item>
            <item key="PCairoPreis">P. Cairo Preis.</item>
            <item key="PCairoSalem">P. Cairo Salem</item>
            <item key="PCairoZenI">P. Cairo Zen. 1</item>
            <item key="PCairoZenII">P. Cairo Zen. 2</item>
            <item key="PCairoZenIII">P. Cairo Zen. 3</item>
            <item key="PCairoZenIV">P. Cairo Zen. 4</item>
            <item key="PCairoZenV">P. Cairo Zen. 5</item>
            <item key="ChartaeLatinaeXII">Chartae Latinae 12</item>
            <item key="PCollYoutieI">P. Coll.Youtie 1</item>
            <item key="PCollYoutieII">P. Coll.Youtie 2</item>
            <item key="PColtNessIII">P. Colt Ness. 3</item>
            <item key="PColI">P. Col. 1</item>
            <item key="PColII">P. Col. 2</item>
            <item key="PColV">P. Col. 5</item>
            <item key="PColVI">P. Col. 6</item>
            <item key="PColVIII">P. Col. 8</item>
            <item key="PColX">P. Col. 10</item>
            <item key="PColZenI">P. Col.Zen. 1</item>
            <item key="PColZenII">P. Col.Zen. 2</item>
            <item key="PCornell">P. Cornell</item>
            <item key="CEML">C.E.M.L.</item>
            <item key="COrdPtol">C.Ord.Ptol.</item>
            <item key="CPJII">C.P.J. 2</item>
            <item key="CPRI">C.P.R. 1</item>
            <item key="CPRV">C.P.R. 5</item>
            <item key="CPRVI">C.P.R. 6</item>
            <item key="CPRVII">C.P.R. 7</item>
            <item key="CPRVIII">C.P.R. 8</item>
            <item key="CPRIX">C.P.R. 9</item>
            <item key="CPRX">C.P.R. 10</item>
            <item key="CPRXIII">C.P.R. 13</item>
            <item key="CPRXIV">C.P.R. 14</item>
            <item key="CPRXV">C.P.R. 15</item>
            <item key="CPRXVIIA">C.P.R. 17A</item>
            <item key="CPRXVIII">C.P.R. 18</item>
            <item key="CPRXIX">C.P.R. 19</item>
            <item key="CPRXX">C.P.R. 20</item>
            <item key="CPRXXII">C.P.R. 22</item>
            <item key="CPRXXIII">C.P.R. 23</item>
            <item key="CPRXXIV">C.P.R. 24</item>
            <item key="PCount">P. Count</item>
            <item key="PCustoms">P. Customs</item>
            <item key="PDiog">P. Diog.</item>
            <item key="PDiosk">P. Diosk.</item>
            <item key="PDryton">P. Dryton</item>
            <item key="PDub">P. Dub.</item>
            <item key="PDura">P. Dura</item>
            <item key="PEdfouI">P. Edfou 1</item>
            <item key="PEireneII">P. Eirene 2</item>
            <item key="PEleph">P. Eleph.</item>
            <item key="PElephDAIK">P. Eleph. D.A.I.K.</item>
            <item key="PEnteuxeis">P. Enteuxeis</item>
            <item key="PErasmI">P. Erasm. 1</item>
            <item key="PErlangen">P. Erlangen</item>
            <item key="PErlDiosp">P. Erl.Diosp.</item>
            <item key="PFay">P. Fay.</item>
            <item key="PFlorI">P. Flor. 1</item>
            <item key="PFlorII">P. Flor. 2</item>
            <item key="PFlorIII">P. Flor. 3</item>
            <item key="PFouad">P. Fouad</item>
            <item key="PFouadCrawford">P. Fouad Crawford</item>
            <item key="PFrankf">P. Frankf.</item>
            <item key="PFreibIII">P. Freib. 3</item>
            <item key="PFreibIV">P. Freib. 4</item>
            <item key="PGenfIIIAufl">P. Genf 1 (2. Aufl.)</item>
            <item key="PGenfII">P. Genf 2</item>
            <item key="PGenfIV">P. Genf 4</item>
            <item key="PGiss">P. Giss.</item>
            <item key="PGissApoll">P. Giss.Apoll.</item>
            <item key="PGot">P. Got.</item>
            <item key="PGrad">P. Grad.</item>
            <item key="PGrauxIII">P. Graux 3</item>
            <item key="PGrenfI">P. Grenf. 1</item>
            <item key="PGrenfII">P. Grenf. 2</item>
            <item key="PGron">P. Gron.</item>
            <item key="PHal">P. Hal.</item>
            <item key="PHambI">P. Hamb. 1</item>
            <item key="PHambII">P. Hamb. 2</item>
            <item key="PHambIII">P. Hamb. 3</item>
            <item key="PHambIV">P. Hamb. 4</item>
            <item key="PHarrauer">P. Harrauer</item>
            <item key="PHarrI">P. Harr. 1</item>
            <item key="PHarrII">P. Harr. 2</item>
            <item key="PHaunII">P. Haun. 2</item>
            <item key="PHaunIII">P. Haun. 3</item>
            <item key="PHeidIV">P. Heid. 4</item>
            <item key="PHeidV">P. Heid. 5</item>
            <item key="PHeidVI">P. Heid. 6</item>
            <item key="PHeidVII">P. Heid. 7</item>
            <item key="PHelsI">P. Hels. 1</item>
            <item key="PHermRees">P. Herm.Rees</item>
            <item key="PHibI">P. Hib. 1</item>
            <item key="PHibII">P. Hib. 2</item>
            <item key="PHorak">P. Horak</item>
            <item key="PIFAOIII">P. I.F.A.O. 3</item>
            <item key="PJandII">P. Jand. 2</item>
            <item key="PJandIII">P. Jand. 3</item>
            <item key="PJandVI">P. Jand. 6</item>
            <item key="PJandVIII">P. Jand. 8</item>
            <item key="PKellisI">P. Kellis 1</item>
            <item key="PKellisIVGrXCVI">P. Kellis 4 Gr. 96</item>
            <item key="PKlnI">P. Köln 1</item>
            <item key="PKlnII">P. Köln 2</item>
            <item key="PKlnIII">P. Köln 3</item>
            <item key="PKlnIV">P. Köln 4</item>
            <item key="PKlnV">P. Köln 5</item>
            <item key="PKlnVI">P. Köln 6</item>
            <item key="PKlnVIII">P. Köln 8</item>
            <item key="PKlnIX">P. Köln 9</item>
            <item key="PKlnX">P. Köln 10</item>
            <item key="PLandlisten">P. Landlisten</item>
            <item key="PLaurII">P. Laur. 2</item>
            <item key="PLaurIII">P. Laur. 3</item>
            <item key="PLaurIV">P. Laur. 4</item>
            <item key="PLilleI">P. Lille 1</item>
            <item key="PLilleII">P. Lille 2</item>
            <item key="PLipsI">P. Lips. 1</item>
            <item key="PLipsII">P. Lips. 2</item>
            <item key="PLondI">P. Lond. 1</item>
            <item key="PLondII">P. Lond. 2</item>
            <item key="PLondIII">P. Lond. 3</item>
            <item key="PLondIV">P. Lond. 4</item>
            <item key="PLondV">P. Lond. 5</item>
            <item key="PLondVI">P. Lond. 6</item>
            <item key="PLondVII">P. Lond. 7</item>
            <item key="PLouvreI">P. Louvre 1</item>
            <item key="PLouvreII">P. Louvre 2</item>
            <item key="PLBatI">P. L.Bat. 1</item>
            <item key="PLBatII">P. L.Bat. 2</item>
            <item key="PLBatIII">P. L.Bat. 3</item>
            <item key="PLBatVI">P. L.Bat. 6</item>
            <item key="PLBatXI">P. L.Bat. 11</item>
            <item key="PLBatXIII">P. L.Bat. 13</item>
            <item key="PLBatXVI">P. L.Bat. 16</item>
            <item key="PLBatXVII">P. L.Bat. 17</item>
            <item key="PLBatXIX">P. L.Bat. 19</item>
            <item key="PLBatXX">P. L.Bat. 20</item>
            <item key="PLBatXXII">P. L.Bat. 22</item>
            <item key="PLBatXXV">P. L.Bat. 25</item>
            <item key="PLBatXXXII">P. L.Bat. 32</item>
            <item key="PLundII">P. Lund 2</item>
            <item key="PLundIV">P. Lund 4</item>
            <item key="PLundVI">P. Lund 6</item>
            <item key="PMedIAuflII">P. Med. 1 Aufl. 2</item>
            <item key="PMertonI">P. Merton 1</item>
            <item key="PMertonII">P. Merton 2</item>
            <item key="PMichael">P. Michael.</item>
            <item key="PMichII">P. Mich. 2</item>
            <item key="PMichIII">P. Mich. 3</item>
            <item key="PMichIVTeilI">P. Mich. 4 Teil 1</item>
            <item key="PMichV">P. Mich. 5</item>
            <item key="PMichVI">P. Mich. 6</item>
            <item key="PMichVII">P. Mich. 7</item>
            <item key="PMichVIII">P. Mich. 8</item>
            <item key="PMichIX">P. Mich. 9</item>
            <item key="PMichX">P. Mich. 10</item>
            <item key="PMichXI">P. Mich. 11</item>
            <item key="PMichXIII">P. Mich. 13</item>
            <item key="PMichXV">P. Mich. 15</item>
            <item key="PMichXVIII">P. Mich. 18</item>
            <item key="PMichZen">P. Mich.Zen.</item>
            <item key="PMilVoglI">P. Mil.Vogl. 1</item>
            <item key="PMilVoglII">P. Mil.Vogl. 2</item>
            <item key="PMilVoglIII">P. Mil.Vogl. 3</item>
            <item key="PMilVoglIV">P. Mil.Vogl. 4</item>
            <item key="MPERXIII">M.P.E.R 13</item>
            <item key="MPERXV">M.P.E.R 15</item>
            <item key="MitteisChrest">Mitteis, Chrest.</item>
            <item key="PMonIII">P. Mon. 3</item>
            <item key="PMonApollo">P. Mon.Apollo</item>
            <item key="PNagHammadi">P. Nag Hammadi</item>
            <item key="PNeph">P. Neph.</item>
            <item key="PNewYorkI">P. New York 1</item>
            <item key="POsloII">P. Oslo 2</item>
            <item key="POsloIII">P. Oslo 3</item>
            <item key="POxyI">P. Oxy. 1</item>
            <item key="POxyII">P. Oxy. 2</item>
            <item key="POxyIII">P. Oxy. 3</item>
            <item key="POxyIV">P. Oxy. 4</item>
            <item key="POxyVI">P. Oxy. 6</item>
            <item key="POxyVII">P. Oxy. 7</item>
            <item key="POxyVIII">P. Oxy. 8</item>
            <item key="POxyIX">P. Oxy. 9</item>
            <item key="POxyX">P. Oxy. 10</item>
            <item key="POxyXII">P. Oxy. 12</item>
            <item key="POxyXIV">P. Oxy. 14</item>
            <item key="POxyXVI">P. Oxy. 16</item>
            <item key="POxyXVII">P. Oxy. 17</item>
            <item key="POxyXVIII">P. Oxy. 18</item>
            <item key="POxyXIX">P. Oxy. 19</item>
            <item key="POxyXX">P. Oxy. 20</item>
            <item key="POxyXXII">P. Oxy. 22</item>
            <item key="POxyXXIV">P. Oxy. 24</item>
            <item key="POxyXXVII">P. Oxy. 27</item>
            <item key="POxyXXXI">P. Oxy. 31</item>
            <item key="POxyXXXIII">P. Oxy. 33</item>
            <item key="POxyXXXIV">P. Oxy. 34</item>
            <item key="POxyXXXVI">P. Oxy. 36</item>
            <item key="POxyXXXVIII">P. Oxy. 38</item>
            <item key="POxyXL">P. Oxy. 40</item>
            <item key="POxyXLI">P. Oxy. 41</item>
            <item key="POxyXXIX">P. Oxy. 42</item>
            <item key="POxyXLIII">P. Oxy. 43</item>
            <item key="POxyXLIV">P. Oxy. 44</item>
            <item key="POxyXLV">P. Oxy. 45</item>
            <item key="POxyXLVI">P. Oxy. 46</item>
            <item key="POxyXLVII">P. Oxy. 47</item>
            <item key="POxyXLVIII">P. Oxy. 48</item>
            <item key="POxyXLIX">P. Oxy. 49</item>
            <item key="POxyL">P. Oxy. 50</item>
            <item key="POxyLI">P. Oxy. 51</item>
            <item key="POxyLIV">P. Oxy. 54</item>
            <item key="POxyLV">P. Oxy. 55</item>
            <item key="POxyLVI">P. Oxy. 56</item>
            <item key="POxyLVII">P. Oxy. 57</item>
            <item key="POxyLVIII">P. Oxy. 58</item>
            <item key="POxyLIX">P. Oxy. 59</item>
            <item key="POxyLX">P. Oxy. 60</item>
            <item key="POxyLXI">P. Oxy. 61</item>
            <item key="POxyLXII">P. Oxy. 62</item>
            <item key="POxyLXIII">P. Oxy. 63</item>
            <item key="POxyLXVII">P. Oxy. 67</item>
            <item key="POxyLXVIII">P. Oxy. 68</item>
            <item key="POxyLXIX">P. Oxy. 69</item>
            <item key="POxyLXX">P. Oxy. 70</item>
            <item key="POxyLXXI">P. Oxy. 71</item>
            <item key="POxyLXXII">P. Oxy. 72</item>
            <item key="POxyHels">P. Oxy.Hels.</item>
            <item key="PPalauRib">P. Palau Rib.</item>
            <item key="PPanop">P. Panop.</item>
            <item key="PPanopBorkowski">P. Panop.Borkowski</item>
            <item key="PParamone">P. Paramone</item>
            <item key="PPetas">P. Petaüs</item>
            <item key="PPetraI">P. Petra 1</item>
            <item key="PPetrII">P. Petr. 2</item>
            <item key="PPetrIII">P. Petr. 3</item>
            <item key="PPetrIIIAufl">P. Petr. 1 (2. Aufl.)</item>
            <item key="PPher">P. Pher.</item>
            <item key="PPhil">P. Phil.</item>
            <item key="PPolitlud">P. Polit. lud.</item>
            <item key="PPragI">P. Prag. 1</item>
            <item key="PPragII">P. Prag. 2</item>
            <item key="PPrincUnivI">P. Princ.Univ. 1</item>
            <item key="PPrincUnivII">P. Princ.Univ. 2</item>
            <item key="PPrincUnivIII">P. Princ.Univ. 3</item>
            <item key="PRainerCent">P. Rainer Cent.</item>
            <item key="PReinI">P. Rein. 1</item>
            <item key="PReinII">P. Rein. 2</item>
            <item key="RevLaws">Rev.Laws</item>
            <item key="PRossGeorgII">P. Ross.-Georg. 2</item>
            <item key="PRossGeorgIII">P. Ross.-Georg. 3</item>
            <item key="PRossGeorgIV">P. Ross.-Georg. 4</item>
            <item key="PRossGeorgV">P. Ross.-Georg. 5</item>
            <item key="PRylII">P. Ryl. 2</item>
            <item key="PRylIV">P. Ryl. 4</item>
            <item key="PSakaon">P. Sakaon</item>
            <item key="SBI">S.B. 1</item>
            <item key="SBIII">S.B. 3</item>
            <item key="SBIV">S.B. 4</item>
            <item key="SBV">S.B. 5</item>
            <item key="SBVI">S.B. 6</item>
            <item key="SBVIII">S.B. 8</item>
            <item key="SBX">S.B. 10</item>
            <item key="SBXII">S.B. 12</item>
            <item key="SBXIV">S.B. 14</item>
            <item key="SBXVI">S.B. 16</item>
            <item key="SBXVIII">S.B. 18</item>
            <item key="SBXX">S.B. 20</item>
            <item key="SBXXII">S.B. 22</item>
            <item key="SBXXIV">S.B. 24</item>
            <item key="SBXXVI">S.B. 26</item>
            <item key="SBXXVIII">S.B. 28</item>
            <item key="PSarap">P. Sarap.</item>
            <item key="PSijp">P. Sijp.</item>
            <item key="PSAAthen">P. S.A.Athen.</item>
            <item key="PSocI">P. Soc. 1</item>
            <item key="PSocIII">P. Soc. 3</item>
            <item key="PSocIV">P. Soc. 4</item>
            <item key="PSocV">P. Soc. 5</item>
            <item key="PSocVI">P. Soc. 6</item>
            <item key="PSocVII">P. Soc. 7</item>
            <item key="PSocVIII">P. Soc. 8</item>
            <item key="PSocIX">P. Soc. 9</item>
            <item key="PSocX">P. Soc. 10</item>
            <item key="PSocXII">P. Soc. 12</item>
            <item key="PSocXIII">P. Soc. 13</item>
            <item key="PSocXIV">P. Soc. 14</item>
            <item key="PSocXV">P. Soc. 15</item>
            <item key="PSocComVI">P. Soc.Com. 6</item>
            <item key="PSocXICongr">P. Soc. XI Congr.</item>
            <item key="PSocXVIICongr">P. Soc. XVII Congr.</item>
            <item key="PSocXXCongr">P. Soc. XX Congr.</item>
            <item key="PSorbII">P. Sorb. 2</item>
            <item key="PSoterichos">P. Soterichos</item>
            <item key="PStaXyla">P. Sta.Xyla</item>
            <item key="PStrasbI">P. Strasb. 1</item>
            <item key="PStrasbII">P. Strasb. 2</item>
            <item key="PStrasbIII">P. Strasb. 3</item>
            <item key="PStrasbIV">P. Strasb. 4</item>
            <item key="PStrasbV">P. Strasb. 5</item>
            <item key="PStrasbVI">P. Strasb. 6</item>
            <item key="PStrasbVII">P. Strasb. 7</item>
            <item key="PStrasbVIII">P. Strasb. 8</item>
            <item key="PStrasbIX">P. Strasb. 9</item>
            <item key="StudPalII">Stud.Pal. 2</item>
            <item key="StudPalIII">Stud.Pal. 3</item>
            <item key="StudPalIIIIIAufl">Stud.Pal. 3 (2. Aufl.)</item>
            <item key="StudPalV">Stud.Pal. 5</item>
            <item key="StudPalVIII">Stud.Pal. 8</item>
            <item key="StudPalX">Stud.Pal. 10</item>
            <item key="StudPalXX">Stud.Pal. 20</item>
            <item key="StudPalXXII">Stud.Pal. 22</item>
            <item key="PTebtI">P. Tebt. 1</item>
            <item key="PTebtII">P. Tebt. 2</item>
            <item key="PTebtIIITeilI">P. Tebt. 3 Teil 1</item>
            <item key="PTebtIIITeilII">P. Tebt. 3 Teil 2</item>
            <item key="PTebtV">P. Tebt. 5</item>
            <item key="PThomas">P. Thomas</item>
            <item key="PTorChoachiti">P. Tor.Choachiti</item>
            <item key="PTurner">P. Turner</item>
            <item key="PUGI">P.U.G. 1</item>
            <item key="PUGII">P.U.G. 2</item>
            <item key="PUGIII">P.U.G. 3</item>
            <item key="UPZI">U.P.Z. 1</item>
            <item key="UPZII">U.P.Z. 2</item>
            <item key="PVars">P. Vars.</item>
            <item key="PVaticAphr">P. Vatic.Aphr.</item>
            <item key="PVindobSalomons">P. Vindob.Salomons</item>
            <item key="PVindobTandem">P. Vindob.Tandem</item>
            <item key="PWashUnivI">P. Wash.Univ. 1</item>
            <item key="PWashUnivII">P. Wash.Univ. 2</item>
            <item key="WilckenChrest">Wilcken, Chrest.</item>
            <item key="PWiscII">P. Wisc. 2</item>
            <item key="PWrzb">P. Würzb.</item>
            <item key="PYadin">P. Yadin</item>
            <item key="PYadinII">P. Yadin 2</item>
            <item key="PYaleI">P. Yale 1</item>
            <item key="PYaleIII">P. Yale 3</item>
            <item key="PZauzich">P. Zauzich</item>
            <item key="OAberd">O. Aberd.</item>
            <item key="OAmst">O. Amst.</item>
            <item key="OAshmShelton">O. Ashm.Shelton</item>
            <item key="OBawitIFAO">O. Bawit IFAO</item>
            <item key="OBerenikeI">O. Berenike 1</item>
            <item key="OBerenikeII">O. Berenike 2</item>
            <item key="OBrssBerl">O. Brüss.-Berl.</item>
            <item key="OBuNjem">O. Bu Njem</item>
            <item key="OCairoGPW">O. Cairo G.P.W.</item>
            <item key="OClaudI">O. Claud. 1</item>
            <item key="OClaudII">O. Claud. 2</item>
            <item key="OClaudIII">O. Claud. 3</item>
            <item key="ODouchIV">O. Douch 4</item>
            <item key="ODouchV">O. Douch 5</item>
            <item key="OEdfouI">O. Edfou 1</item>
            <item key="OEdfouII">O. Edfou 2</item>
            <item key="OEdfouIII">O. Edfou 3</item>
            <item key="OElephDAIK">O. Eleph.D.A.I.K.</item>
            <item key="OFay">O. Fay.</item>
            <item key="OFlorida">O. Florida</item>
            <item key="OHeid">O. Heid.</item>
            <item key="OKellis">O. Kellis</item>
            <item key="OKrokI">O. Krok. 1</item>
            <item key="OLeid">O. Leid.</item>
            <item key="OLund">O. Lund.</item>
            <item key="OMeyer">O. Meyer</item>
            <item key="OMichI">O. Mich. 1</item>
            <item key="OGrNarmuthisI">O. Gr.Narmuthis 1</item>
            <item key="OOntMusII">O. Ont.Mus. 2</item>
            <item key="OStrasb">O. Strasb.</item>
            <item key="OTaitI">O. Tait 1</item>
            <item key="OTaitII">O. Tait 2</item>
            <item key="OTaitIII">O. Tait 3</item>
            <item key="OTheb">O. Theb.</item>
            <item key="OWilbBrk">O. Wilb.-Brk.</item>
            <item key="OWilckenI">O. Wilcken 1</item>
            <item key="OWilckenII">O. Wilcken 2</item>
            <item key="TavoletteVarie">Tavolette Varie</item>
        </list>
    </xsl:variable>
    
    <xsl:template match="text:h[string(.)=('Publikation', 'Spezial')]">
        <xsl:copy>
            <xsl:apply-templates select="@*"/>
            <xsl:variable name="key" select="string(following-sibling::table:table[1]/@table:style-name)"/>
            <xsl:variable name="publication" select="string($PUBLICATIONS//tei:item[@key=$key])"/>
            <xsl:value-of select="$publication"/>
        </xsl:copy>
    </xsl:template>

    <xsl:template match="table:table-header-rows">
        <xsl:apply-templates select="@*|node()"/>
    </xsl:template>

    <xsl:template match="table:table-row">
        <xsl:message select="substring-before(@table:style-name, '.')"/>
        <xsl:comment select="substring-before(@table:style-name, '.')"/>
    </xsl:template>

    <!-- COPY -->
    <xsl:template match="@* | node()">
        <xsl:copy>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:copy>
    </xsl:template>

</xsl:stylesheet>