PapyrillioBeehive_Archive:
    path:  /archive
    controller: App\Controller\DefaultController::archive

PapyrillioBeehive_About:
    path:  /about
    controller: App\Controller\DefaultController::about 

PapyrillioBeehive_Contact:
    path:  /contact
    controller: App\Controller\DefaultController::contact 

PapyrillioBeehive_Help:
    path:  /help
    controller: App\Controller\DefaultController::help 

PapyrillioBeehive_Home:
    path:  /
    controller: App\Controller\DefaultController::index 

PapyrillioBeehive_Homepage:
    path:  /hello/{name}
    controller: App\Controller\DefaultController::index 

# NumberWizard

PapyrillioBeehive_NumberWizard:
    path:  /numberWizard
    controller: App\Controller\NumberWizardController::index

PapyrillioBeehive_NumberWizardLookup:
    path:  /numberWizard/lookup
    controller: App\Controller\NumberWizardController::lookup

PapyrillioBeehive_NumberWizardAutocompleteDdb:
    path:  /numberWizard/autocomplete/ddb
    controller: App\Controller\NumberWizardController::autocompleteDdb

# Register

PapyrillioBeehive_RegisterShow:
    path:  /register/show/{id}
    controller: App\Controller\RegisterController::show 
    requirements:
      id: '\d+'

PapyrillioBeehive_RegisterAutocomplete:
    path:  /register/autocomplete/{id}
    controller: App\Controller\RegisterController::autocomplete
    defaults:
        id: 0

PapyrillioBeehive_RegisterautoCompleteDddb:
    path:  /register/autocompleteDdb
    controller: App\Controller\RegisterController::autocompleteDdb

PapyrillioBeehive_RegisterShowAssignments:
    path:  /register/showAssignments/{correctionId}
    controller: App\Controller\RegisterController::showAssignments
    requirements:
      correctionId: '\d+'

PapyrillioBeehive_RegisterRevokeAssignment:
    path:  /register/revokeAssignment/{registerId}/{correctionId}
    controller: App\Controller\RegisterController::revokeAssignment
    requirements:
      registerId: '\d+'
      correctionId: '\d+'

PapyrillioBeehive_RegisterAssign:
    path:  /register/assign/{registerId}/{correctionId}
    controller: App\Controller\RegisterController::assign
    requirements:
      registerId: '\d+'
      correctionId: '\d+'

PapyrillioBeehive_RegisterCreate:
    path:  /register/create
    controller: App\Controller\RegisterController::create

PapyrillioBeehive_RegisterCreateAndAssign:
    path:  /register/createAndAssign/{correctionId}
    controller: App\Controller\RegisterController::createAndAssign
    requirements:
      correctionId: '\d+'

PapyrillioBeehive_RegisterWizard:
    path:  /registerWizard/{id}
    controller: App\Controller\RegisterController::wizard
    requirements:
      correctionId: '\d+'

PapyrillioBeehive_RegisterApiary:
    path:  /registerApiary/{id}
    controller: App\Controller\RegisterController::apiary
    requirements:
      correctionId: '\d+'

# Report

PapyrillioBeehive_Report:
    path:  /report
    controller: App\Controller\ReportController::leiden
    defaults:
        compilationVolume: 13

PapyrillioBeehive_ReportLeiden:
    path:  /report/leiden/{compilationVolume}
    controller: App\Controller\ReportController::leiden
    defaults:
        compilationVolume: 13

PapyrillioBeehive_ReportSnippet:
    path:  /report/snippet/leiden/{id}
    controller: App\Controller\ReportController::leidenSnippet 

PapyrillioBeehive_ReportOverview:
    path:  /report/overview/{compilationVolume}
    controller: App\Controller\ReportController::overview
    defaults:
        compilationVolume: 13

PapyrillioBeehive_ReportPrint:
    path:  /report/print/{compilationVolume}/{editionId}
    controller: App\Controller\ReportController::print
    defaults:
        compilationVolume: 13
        editionId: 0

PapyrillioBeehive_ReportPdf:
    path:  /report/pdf/{compilationVolume}/{editionId}
    controller: App\Controller\ReportController::pdf
    defaults:
        compilationVolume: 13
        editionId: 0

# Log

PapyrillioBeehive_Log:
    path:  /log
    controller: App\Controller\LogController::showDeletedCorrections

# Correction

PapyrillioBeehive_CorrectionList:
    path:  /correction/list
    controller: App\Controller\CorrectionController::list 

PapyrillioBeehive_CorrectionPrint:
    path:  /correction/print
    controller: App\Controller\CorrectionController:list
    defaults:
        print: true

PapyrillioBeehive_CorrectionShow:
    path:  /correction/show/{id}
    controller: App\Controller\CorrectionController::show 

PapyrillioBeehive_CorrectionTest:
    path:  /correction/test/{id}
    controller: App\Controller\CorrectionController::test 

PapyrillioBeehive_CorrectionDelete:
    path:  /correction/delete/{id}
    controller: App\Controller\CorrectionController::delete 

PapyrillioBeehive_CorrectionNew:
    path:  /correction/new
    controller: App\Controller\CorrectionController::new 

PapyrillioBeehive_CorrectionUpdate:
    path:  /correction/update/{id}
    controller: App\Controller\CorrectionController::update 

PapyrillioBeehive_CorrectionLinkSnippet:
    path:  /correction/snippet/link/{id}
    controller: App\Controller\CorrectionController::snippetLink 

# Edition

PapyrillioBeehive_EditionList:
    path:  /edition/list
    controller: App\Controller\EditionController::list 

PapyrillioBeehive_EditionShow:
    path:  /edition/show/{id}
    controller: App\Controller\EditionController::show 

PapyrillioBeehive_EditionDelete:
    path:  /edition/delete/{id}
    controller: App\Controller\EditionController::delete 

PapyrillioBeehive_EditionNew:
    path:  /edition/new
    controller: App\Controller\EditionController::new 

PapyrillioBeehive_EditionUpdate:
    path:  /edition/update
    controller: App\Controller\EditionController::update 

# Task

PapyrillioBeehive_TaskDelete:
    path:  /task/delete/{id}
    controller: App\Controller\TaskController::delete 

PapyrillioBeehive_TaskSnippet:
    path:  /task/snippet/{id}
    controller: App\Controller\TaskController::snippet 

PapyrillioBeehive_TaskNew:
    path:  /task/new
    controller: App\Controller\TaskController::new 

PapyrillioBeehive_TaskUpdate:
    path:  /task/update/{id}
    controller: App\Controller\TaskController::update 

# Index

PapyrillioBeehive_IndexDelete:
    path:  /index/delete/{id}
    controller: App\Controller\IndexController::delete 

PapyrillioBeehive_IndexSnippet:
    path:  /index/snippet/{id}
    controller: App\Controller\IndexController::snippet 

PapyrillioBeehive_IndexNew:
    path:  /index/new
    controller: App\Controller\IndexController::new 

PapyrillioBeehive_IndexUpdate:
    path:  /index/update/{id}
    controller: App\Controller\IndexController::update 

# System

PapyrillioBeehive_SystemSort:
    path:  /system/sort/{editionId}
    controller: App\Controller\SystemController::sort
    defaults:
        editionId: 0 

PapyrillioBeehive_SystemCheckSort:
    path:  /system/checkSort/{id}
    controller: App\Controller\SystemController::checkSort

# IndexEntry

PapyrillioBeehive_IndexEntryGhostword:
    path:  /ghostwords
    controller: App\Controller\IndexEntryController::list
    defaults:
        type: 'Ghostword'

PapyrillioBeehive_IndexEntryNew:
    path:  /newwords
    controller: App\Controller\IndexEntryController::list
    defaults:
        type: 'Neues Wort'

PapyrillioBeehive_IndexEntry:
    path:  /idx/{type}
    controller: App\Controller\IndexEntryController::list
    defaults:
        type: 'Neues Wort'

# Apiary

PapyrillioBeehive_Apiary:
    path:  /browse
    controller: App\Controller\ApiaryController::index
    defaults:
        format: html

PapyrillioBeehive_ApiaryHoney:
    path:  /{type}/{id}/{format}
    controller: App\Controller\ApiaryController::honey
    defaults:
        format: html
    requirements:
      type: '(tm|hgv|ddb|biblio|bl|register|boep|volume|collection)'
      format: '(plain|xml|html|rdf|json|latex)'

# Security / User

PapyrillioBeehive_Registration:
    path: /registration
    controller: App\Controller\RegistrationController::index

PapyrillioBeehive_Logout:
    path: /logout
    methods: GET

PapyrillioBeehive_Login:
    path: /login
    controller: App\Controller\SecurityController::login

PapyrillioBeehive_UserChangePassword:
    path: /user/changePassword
    controller: App\Controller\UserController::changePassword

PapyrillioBeehive_UserEditProfile:
    path: /user/editProfile
    controller: App\Controller\UserController::editProfile

PapyrillioBeehive_UserList:
    path: /user/list
    controller: App\Controller\UserController::list

PapyrillioBeehive_UserNew:
    path: /user/new
    controller: App\Controller\UserController::new

PapyrillioBeehive_UserShow:
    path: /user/show/{id}
    controller: App\Controller\UserController::show
    requirements:
      id: '\d+'

PapyrillioBeehive_UserPassword:
    path: /user/password
    controller: App\Controller\UserController::password
