Papyrillio\BeehiveBundle\Entity\Compilation:
    type: entity
    table: compilation
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        volume:
            type: integer
        fascicle:
            type: integer
            nullable: true
        title:
            type: text
        start:
            type: date
            nullable: true
        end:
            type: date
            nullable: true
        publication:
            type: date
            nullable: true
    oneToMany:
        corrections:
            targetEntity: Correction
            mappedBy: compilation
    # don't forget to init the collection in entity __construct() method