Papyrillio\BeehiveBundle\Entity\Correction:
    type: entity
    table: correction
    gedmo:
        loggable
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        source:
            type: integer
        text:
            type: string
            length: 64
        tm:
            type: integer
        folder:
            type: integer
        hgv:
            type: string
            length: 64
        ddb:
            type: string
            length: 64
        collection:
            type: string
            length: 64
        volume:
            type: string
            length: 64
        document:
            type: string
            length: 64
        position:
            type: text
            nullable: true
            gedmo:
                - versioned
        description:
            type: text
            gedmo:
                - versioned
    manyToOne:
        edition:
            targetEntity: Edition
            inversedBy: corrections
            joinColumn:
                name: edition_id
                referencedColumnName: id
                nullable: false

        compilation:
            targetEntity: Compilation
            inversedBy: corrections
            joinColumn:
                name: compilation_id
                referencedColumnName: id
                nullable: false
    oneToMany:
        tasks:
            targetEntity: Task
            mappedBy: correction
    # don't forget to init the collection in entity __construct() method