Papyrillio\BeehiveBundle\Entity\Correction:
    type: entity
    table: correction
    gedmo:
        loggable
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        source:
            type: integer
            nullable: true
        text:
            type: string
            length: 64
        tm:
            type: integer
            nullable: true
        folder:
            type: integer
            nullable: true
        hgv:
            type: string
            length: 64
            nullable: true
        ddb:
            type: string
            length: 64
            nullable: true
        collection:
            type: string
            length: 64
            nullable: true
        volume:
            type: string
            length: 64
            nullable: true
        document:
            type: string
            length: 64
            nullable: true
        position:
            type: text
            nullable: true
            gedmo:
                - versioned
        description:
            type: text
            gedmo:
                - versioned
        status:
            type: text
            gedmo:
                - versioned
        creator:
            type: text
        created:
            type: datetime
    manyToOne:
        edition:
            targetEntity: Edition
            inversedBy: corrections
            joinColumn:
                name: edition_id
                referencedColumnName: id
                nullable: false

        compilation:
            targetEntity: Compilation
            inversedBy: corrections
            joinColumn:
                name: compilation_id
                referencedColumnName: id
                nullable: false
    oneToMany:
        tasks:
            targetEntity: Task
            mappedBy: correction
    # don't forget to init the collection in entity __construct() method