Papyrillio\BeehiveBundle\Entity\Register:
    type: entity
    table: register
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        hgv:
            type: string
            length: 64
            nullable: true
        tm:
            type: integer
            nullable: true
        folder:
            type: integer
            nullable: true
        ddb:
            type: string
            length: 64
            nullable: true
        collection:
            type: string
            length: 64
            nullable: true
        volume:
            type: string
            length: 64
            nullable: true
        document:
            type: string
            length: 64
            nullable: true
    manyToMany:
        corrections:
            targetEntity: Correction
            joinTable:
              name: correction_register
              joinColumns:
                register_id:
                  referencedColumnName: id
              inverseJoinColumns:
                correction_id:
                  referencedColumnName: id
    # don't forget to init the collection in entity __construct() method