Papyrillio\BeehiveBundle\Entity\Task:
    type: entity
    table: task
    gedmo:
        loggable
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        category:
            type: string
            length: 64
        description:
            type: text
            gedmo:
                - versioned
        cleared:
            type: datetime
            nullable: true
            gedmo:
                - versioned
    manyToOne:
        correction:
            targetEntity: Correction
            inversedBy: tasks
            joinColumn:
                name: correction_id
                referencedColumnName: id
                nullable: false